### ISSUE TITLE
Error: No match was found for the specified search criteria and module name 'OpenSSHUtils'

### ISSUE THREAD

**Issue by JoshSnider** [MicrosoftDocs/windowsserverdocs#5408] opened 2021-03-26 21:22 UTC
The document references `OpenSSHUtils` as the tooling solution for deploying public keys to the server, but this tool is no longer available (it seems it has been deprecated). See: https://stackoverflow.com/questions/62873521/powershell-opensshutils

Please update these documents with new instructions for deploying public keys.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by illfated** [comment] 2021-03-27 20:23
I know, it has taken a long time to get the documentation updated to match the current status. This has been reported before and also has at least 1 Pull Request to have the documentation updated accordingly, but it seems to take much more time than first anticipated.

Also, duplicate of the following list of issue tickets:

- **OpenSSHUtils is deprecated** -- #3806 opened on Jan 28, 2020 by FizzBuzz791
- **PubKey Auth not working [solution]** -- #3828 opened on Jan 31, 2020 by ackvf
- **Outdated instructions?** -- #4023 by RussKeldorph was closed on Sep 2, 2020
- **OpenSSHUtils Not Needed** -- #4345 opened on May 14, 2020 by gynnantonix
- **Unable to configure OpenSSH for public key auth following docs** -- #4518 opened on Jun 20, 2020 by jaraco
- **Instructions provided ends with an error** -- #4598 opened on Jun 28, 2020 by jyavenard
- **Out-of-date - OpenSSHUtils no longer available.** -- #4622 opened on Jul 8, 2020 by Jammrock
- **More documentation required** -- #4634 opened on Jul 11, 2020 by garylawuk
- **OpenSSHUtils install reference no longer valid** -- #4690 opened on Aug 1, 2020 by wrjohnson
- **OpenSSHUtils got unlisted from the PowerShell gallery** -- #4702 opened on Aug 5, 2020 by jagraveldinger
- **Does not list possible ssh commands** -- #4726 opened on Aug 16, 2020 by morgzz
- **ssh-agent service not installed upon installation of OpenSSH Server or Client** -- #4729 by ThatNerdyPikachu was closed on Oct 10, 2020
- **Nope. First example errors out.** -- #4743 opened on Aug 22, 2020 by boomalator
- **Error when following instructions to install OpenSSHUtils** -- #4770 opened on Aug 31, 2020 by c0f
- **OpenSSHUtils module does not exist** -- #4787 opened on Sep 4, 2020 by oliversalzburg
- **Does not explain how to ensure keys get reloaded to agent on boot** -- #4858 opened on Sep 30, 2020 by g24swint
- **Private keys from the ssh-agent can be accessed** -- #4871 opened on Oct 2, 2020 by stefanfritsch
- **Install-Module OpenSSHUtils failure** -- #4893 opened on Oct 8, 2020 by LeeJenkins
- **Does ssh-agent on windows have persistent storage of ssh keys?** -- #4946 opened on Oct 27, 2020 by zaaj
- **OpenSSHTools doesn't exist anymore on powershell gallery** -- #4948 opened on Oct 28, 2020 by JustinGrote
- **Clarification needed** -- #5000 opened on Nov 10, 2020 by conyg
- **OpenSSHUtils has been delisted** -- #5068 by esc was closed on Dec 1, 2020
- **Update suggestion of OpenSSHUtils** -- #5080 by aamir0 was closed on Dec 4, 2020
- **These instructions do not work on Windows 10 20h2** -- #5138 opened on Dec 19, 2020 by mihai-preda
- **Out of date - Repair-AuthorizedKeyPermission** -- #5395 opened 4 days ago by nekdima

**Comment by illfated** [comment] 2021-03-27 20:24
See Pull Request **update OpenSSH key management** #4788 for a possible solution to your report.

**Comment by dknappettmsft** [comment] 2021-06-04 11:36
Thanks for submitting this issue. I have reworked this document to remove or replace parts that are no longer relevant or correct based on this and several other issues raised for this page.

The changes should be visible in around 6-12 hours.

#please-close

**Closed by dknappettmsft** 2021-06-04 11:36 UTC
Labels: Pri1, administration/tech, windows-server/prod
