### ISSUE TITLE
Unable to download 1.2.1275

### ISSUE THREAD

**Issue by wimkestens** [MicrosoftDocs/windowsserverdocs#4830] opened 2020-09-18 09:59 UTC
The link returns an error.  All other versions are ok.

**Comment by illfated** [comment] 2020-09-18 17:05
Duplicate of #4831 (**Not able to download 1.2.1275**).

Ticket #4831 contains the necessary page reference.

#please-close

**Comment by illfated** [comment] 2020-09-22 22:26
#please-close

**Comment by illfated** [comment] 2020-11-23 19:54
#please-close

**Closed by illfated** 2020-11-23 19:54 UTC
Labels: Pri3
