### ISSUE TITLE
Grammer error

### ISSUE THREAD

**Issue by wzcgh2019** [MicrosoftDocs/windowsserverdocs#6288] opened 2022-02-21 03:23 UTC
[Enter feedback here]
To view the detailed cluster quorum configuration, you can **you** use the Validate a Configuration Wizard, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de0ec0e0-b3ad-c222-4a3d-940a7c6d8cc3
* Version Independent ID: 11bf5350-4a4f-8468-51c8-c8075e627164
* Content: [Configure and manage the quorum in a failover cluster](https://docs.microsoft.com/en-us/windows-server/failover-clustering/manage-cluster-quorum)
* Content Source: [WindowsServerDocs/failover-clustering/manage-cluster-quorum.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/failover-clustering/manage-cluster-quorum.md)
* Product: **windows-server**
* Technology: **failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by ManikaDhiman** [comment] 2022-02-28 21:30
Hi @wzcgh2019. Thanks for pointing out that there's an extra "you" in the sentence. The issue is now fixed via PR https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/2733. The update will be live after the next publishing pass. Thanks!

**Comment by ManikaDhiman** [comment] 2022-02-28 21:30
#please-close

**Closed by ManikaDhiman** 2022-02-28 21:30 UTC
Labels: Pri1, windows-server/prod, failover-clustering/tech
