### ISSUE TITLE
More than one ellipsis display option in use

### ISSUE THREAD

**Issue by crisman** [MicrosoftDocs/windowsserverdocs#7331] opened 2023-06-15 20:45 UTC
There is only one ellipsis display option in the docs here:

https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/command-line-syntax-key

There are at least two ellipsis display options in use:

- `…` examples:
  - https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/typeperf
  - https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/tracerpt
- `...` examples:
  - https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/copy
  - command line `help` and `/?` output:
    - `help copy`
    - `typeperf /?`
    - `tracerpt /?`

**Comment by Xelu86** [comment] 2023-06-15 21:38
Hey crisman,

We are investigating this as it may or may not be an error in the way `copy` command is displaying the ellipses.

**Comment by Xelu86** [comment] 2023-06-15 22:40
Hey crisman,

Thank you for your feedback.

Upon investigation, the issue is with the typeperf.md page itself. I thought it was a strange unicode issue during testing but was wrong. VSCode has a default font of "Consolas, 'Courier New', monospace".

Testing this in another environment, it appears that a _different_ monospace font was used just for the ellipses. Copy/Pasting the data between the 2 provided this insight. We have corrected the affected page with changes being live the next business day. We'll now be closing this thread.

Thank you and have a most pleasant day.
#please-close

**Closed by Xelu86** 2023-06-15 22:40 UTC
Labels: Pri3
