### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by AndreasL53** [MicrosoftDocs/windowsserverdocs#12] opened 2017-04-29 05:08 UTC
Is there a typo in the last couple of Powershell commands? 

The provided command refers to -ZoneScope "AmericaZoneScope":
Add-DnsServerQueryResolutionPolicy -Name "AmericaPolicy" -Action ALLOW -ClientSubnet "eq,AmericaSubnet" -ZoneScope "**AmericaZoneScope,1**" -ZoneName "woodgrove.com"

However, the instructions before that actually said that we shall create a ZoneScope called **USZoneScope** - not AmericaZoneScope:
Add-DnsServerZoneScope -ZoneName "woodgrove.com" -Name "USZoneScope"

**Comment by jamesmci** [comment] 2017-05-04 17:14
Thanks for pointing this out, Andreas - the issue is now fixed and should be live on the Web later today, 5/4.

**Comment by lizap** [comment] 2017-05-05 17:47
@AndreasL53 - Hi, Andreas, the fixes are now live:

https://docs.microsoft.com/en-us/windows-server/networking/dns/deploy/primary-geo-location
https://docs.microsoft.com/en-us/windows-server/networking/dns/deploy/primary-secondary-geo-location

**Closed by lizap** 2017-05-05 17:47 UTC
