### ISSUE TITLE
Switching local virtual desktops while RDP has focus

### ISSUE THREAD

**Issue by Wardrop** [MicrosoftDocs/windowsserverdocs#2324] opened 2019-01-30 04:31 UTC
Windows 10's virtual desktop feature and RDP seem to be a match made in heaven, allowing - at least in theory - one to be able to quickly cycle between full-screen remote desktop sessions. The problem is, the WIN + CTRL + left/right hotkeys don't work while the remote desktop session as focus. The only way to get it to work is to either change the "Apply windows key combinations" setting in the RDP client (which then prevents ALT + TAB and other functions), or to first press CTRL + ALT + HOME to return focus to the local computer, and then using the WIN + CTRL + left/right arrow key combination to switch virtual desktops.

Obviously neither of these solution is ideal. I'm hoping Microsoft devs could consider treating the desktop switching hotkey like they do CTRL + ALT + DEL, where CTRL + ALT + DEL is always invoked on the local computer, and an alternative hotkey (CTRL + ALT + END) is used to invoke the same action on the remote computer. In this case, pressing WIN + CTRL + left/right keys would always switch desktops on the local computer, and there'd be some alternative hotkey to switch virtual desktops on the remote computer, such as WIN + CTRL + ALT + left/right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588d12d1-fdd1-892a-eb5e-9e2d86302368
* Version Independent ID: 5eceac91-1d90-a663-2856-19e13da59351
* Content: [Remote Desktop clients](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by pajenterprisesllc** [comment] 2019-02-27 07:39
keeping you all  up date with my desktop service

**Comment by arbatgradnja** [comment] 2019-03-09 20:35
error

**Comment by Jarusss** [comment] 2019-04-13 21:15
Confirm. It would be nice if Virtual Desktop would work during RDP session. Right now (unfortunatelly) the only solution is to have second monitor.

**Comment by stevenvolckaert** [comment] 2019-11-08 10:47
+1. This would be very useful indeed.

**Comment by Harrioson** [comment] 2019-11-27 09:17
What is Microsoft OneDrive? Microsoft One drive is a place for everything (hardware)
https://www.techsovibe.com/one-drive/

**Comment by crstnbr** [comment] 2020-03-18 08:05
+100

**Comment by ScottishRoss** [comment] 2020-03-23 11:49
Is there a way to vote for this feature?

**Comment by JesperJ** [comment] 2020-03-23 12:42
+1

**Comment by dannygoulder** [comment] 2020-03-28 06:27
I think it would be great if mstsc could allow you to configure which key combinations are sent to the remote machine

**Comment by Kareltje1980** [comment] 2020-04-15 09:35
+1

**Comment by StumptownRider** [comment] 2020-04-27 19:01
+1

**Comment by Carlos487** [comment] 2020-04-29 14:07
+1 I found out that trackpad gestures are not forwarded so if you have laptop you can switch that way

**Comment by ramonsmits** [comment] 2020-05-21 16:26
Even BETTER if Windows Adopted this in combination with how MacOS works. Fullscreen in MacOS is automatically a desktop between which you can easily switch with the key shortcut or a 4 finger swipe.

But yes, for now just make CTRL+WIN+LEFT/RIGHT work from the topmost desktop!

**Comment by bsivanov** [comment] 2020-06-02 06:02
The workaround I've found useful is:
- On one of the virtual desktops, use only thr RDP window.
- When the focus is captured inside the Remote Desktop window (we are working on the remote machine), use `Ctrl`+`Alt`+`Home` to move the focus to the RDP window on the _local_ machine.
- Then use `Ctrl`+`Win`+Arrows to switch the virtual desktop on the local machine. 

Still I've not found a way to move the focus from the local machine to the remote machine, using only the keyboard - as `Ctrl`+`Win`+Arrows only focuses the RDP window but doesn't move the focus inside.

**Comment by oryandunn** [comment] 2021-01-20 05:48
> Even BETTER if Windows Adopted this in combination with how MacOS works. Fullscreen in MacOS is automatically a desktop between which you can easily switch with the key shortcut or a 4 finger swipe.
> 
> But yes, for now just make CTRL+WIN+LEFT/RIGHT work from the topmost desktop!

THIS!

I hadn't ever used MacOS before I had to work on my sisters older MacBook here recently.  In the course of testing, I started using RDP so I would use her laptop to remote into work.  I love that full screening an app automatically puts that full screen on a new virtual desktop, and I love how quick the 3 finger swipe is to switch between full screen apps.  Super quick to switch between several open RDP sessions and a full screen youtube video and the MacOS desktop at the same time.

For a complete setup for my normal desktop, there would need to be a host key combo that always worked to switch virtual desktops

**Comment by pgurenko** [comment] 2021-06-07 19:39
+1

**Comment by dut00** [comment] 2021-06-25 12:15
That's what I need! +1

**Comment by askvnx** [comment] 2021-08-25 05:11
Adding this so anyone like me looking for an alternative solution can use this method, it has one downside, the client RDP session will lose it's Windows key combinations.

Using Windows 10 Virtual Desktops I have three desktops running.  The first has my main desktop, the other two have two different RDP sessions.  Each RDP session is started with the following setting, expand 'Show Options', then in 'Local Resources' I have 'Apply Windows key combinations:' set to 'On this computer'

Once set and running I can easily switch with all three desktops using the CTRL+WIN+LEFT/RIGHT combination.  Again, you lose the WIN key combos within the RDP.  Works for me, hope it helps you.

**Comment by IngridAtMicrosoft** [comment] 2021-10-16 00:30
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Closed by IngridAtMicrosoft** 2021-10-16 00:30 UTC
Labels: Pri2, windows-server-threshold/prod

**Comment by seflerZ** [comment] 2022-05-03 02:41
When using a precision touchpad, you will be able to switch virutal desktops in RDP by using four finger swipe.

**Comment by ramonsmits** [comment] 2022-05-03 07:50
> When using a precision touchpad, you will be able to switch virutal desktops in RDP by using four finger swipe.

@seflerZ Are you talking about switching virtual desktops of the connected machine within the RDP session or on the Windows host OS?

**Comment by seflerZ** [comment] 2022-05-04 13:09
@ramonsmits You can switch host virtual desktop even when you're in RDP desktop right now. This is what this issue what. Still I don't find a way with the keyboard.

**Comment by seflerZ** [comment] 2022-05-05 06:53
@ramonsmits This issue was read "The problem is, the WIN + CTRL + left/right hotkeys don't work while the remote desktop session as focus". When you have a precision touchpad, switch host virtual desktop works with finger gesture. You can have a try.

**Comment by ramonsmits** [comment] 2022-05-05 07:37
> When you have a precision touchpad, switch host virtual desktop works with finger gesture. You can have a try.

@seflerZ I don't have a precision touchpad on my Windows workstation but now I understand that 4-finger swiping will switch desktops on the host. Thanks for clarifying.

**Comment by askvnx** [comment] 2022-05-06 06:17
I got around it by changing this before I start my remote sessions...
[image: image.png]


*Valentine Xavier*



*Mobile**:* +61 414 275 869

*Email:* ***@***.***


*http://au.linkedin.com/in/valentinexavier
<http://au.linkedin.com/in/valentinexavier>*





This message and any attachment is confidential and may be privileged or
otherwise protected from disclosure. If you have received it by mistake
please let us know by reply and then delete it from your system; you should
not copy the message or disclose its contents to anyone.

**Comment by seflerZ** [comment] 2022-05-09 01:47
@askvnx Sorry but your image can not be displayed, would you please post it again?

**Comment by askvnx** [comment] 2022-05-09 05:29
If you can't see the image then in RDP Options for your connection, goto
the 'Local Resources' tab, and under 'Keyboard'-'Apply Windows key
combinations', I set it to 'On this computer'   You miss out on being able
to use the windows key on the remote session, but it will help you to
switch desktops on the host PC.  I have several RDP sessions running at the
same time, and each on a separate desktop, so I can quickly switch between
the RDP sessions and the host pc using the WIN + CTRL + left/right hotkeys.

[image: image.png]


*Valentine Xavier*



*Mobile**:* +61 414 275 869

*Email:* ***@***.***


*http://au.linkedin.com/in/valentinexavier
<http://au.linkedin.com/in/valentinexavier>*





This message and any attachment is confidential and may be privileged or
otherwise protected from disclosure. If you have received it by mistake
please let us know by reply and then delete it from your system; you should
not copy the message or disclose its contents to anyone.

**Comment by ramonsmits** [comment] 2022-05-09 09:09
> You miss out on being able to use the windows key on the remote session, but it will help you to switch desktops on the host PC.

A good tip if your more in a "view only" session.

**Comment by gdh1995** [comment] 2022-08-02 02:12
>  goto the 'Local Resources' tab, and under 'Keyboard'-'Apply Windows key combinations', I set it to 'On this computer' 

I find this issue today. I do want to use most shortcuts including `Alt+Tab` and `Win+<AnySingleKey>` on the remote Windows, and just expect a keyboard shortcut to move focus back to my client desktop. So this option can't help.

I've searched in Google for many times, but there's no reliable way to switch focus between local and remote desktops - I learned that "a first `Ctrl+Alt+Home` can focus the RDP title bar", but there seems no way to "focus content of a remote desktop from the title bar" when I switch focus onto RDP.

Could someone help me? It will still help even if I have to press two or more keyboard shortcuts to switch local virtual desktops from a focused RDP.

**Comment by lovitus** [comment] 2022-11-12 04:22
help needed !!!
yes , press `ctrl+ alt+ home`  before `switch virtual desktop` is work, when `has connection bar`.
but , I use RDCM client to connect to my multiple clients , not full screen mode but `grab all keystokes`.
I cant find any way to fast switch virtual desktops, only to buy a `magic touchpad` just for few fingers gesture, only one purpose.
only thing i want , just to keep " ctrl win arrow" keystroke only on my host machine.
