### ISSUE TITLE
Add Windows 11 Enterprise to supported Client OS list

### ISSUE THREAD

**Issue by bartmgithub** [MicrosoftDocs/windowsserverdocs#6477] opened 2022-05-23 08:49 UTC
Please add Windows 11 as supported client operating system for Direct Access

snippet from FAQ
Is DirectAccess supported on Windows 11? 
The remote access story for Windows 11 is not fundamentally changing. Like in Windows 10, Windows 11 supports secure remote access using multiple technologies, including TLS and IPsec. “Always-On VPN” remains the preferred VPN infrastructure extensible by VPN partners with plug-ins from the Microsoft Store. Customers can also use IPsec-based VPNs. Microsoft is investing in supporting a cloud-first world. Microsoft recommends moving to “Always-On VPN” for customers using DirectAccess, as they migrate clients to Windows 11, eventually in combination with Azure VPN. Microsoft maintains DirectAccess in Windows 11 and Windows Server to allow customers with an existing Direct Access deployment to migrate away from DirectAccess as they migrate to Windows 11 but is not making further investments. Documentation comparing Always-On VPN functionality with DirectAccess functionality, as well as deployment guidance, is available at [Always On VPN documentation | Microsoft Docs](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa82e6ef-7f35-9672-2ca3-9006de31b2cf
* Version Independent ID: 1dca040b-d5ba-8449-627b-b3069bd9be0e
* Content: [DirectAccess](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/directaccess/directaccess)
* Content Source: [WindowsServerDocs/remote/remote-access/directaccess/DirectAccess.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-access/directaccess/DirectAccess.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by anaharris-ms** [comment] 2022-11-15 15:11
Duplicate of https://github.com/MicrosoftDocs/windowsserverdocs/issues/6229

**Comment by Xelu86** [comment] 2023-01-17 23:08
#assign:xelu86

**Comment by Xelu86** [comment] 2023-01-17 23:22
Hey @nonakaji,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change was made adding Windows 11 Enterprise as a supported OS for Direct Access. Changes are live. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close

**Closed by Xelu86** 2023-01-17 23:22 UTC
Labels: Pri1, windows-server/prod, remote/tech
