### ISSUE TITLE
This page is a duplicate

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/windowsserverdocs#6335] opened 2022-03-09 21:32 UTC
[This](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/design/best-practices-for-secure-planning-and-deployment-of-ad-fs) page is titled the same as this [newer version](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/best-practices-securing-ad-fs) of the document.

I get that this one is within the context of 2012, but the title / topic is not version specific, or if someone feels that it is, I suggest a different title so that they aren't stepping on each other's toes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 343cf896-bed0-5f26-aa83-7feff8b9e1da
* Version Independent ID: 101bb4cb-3285-0a76-1f98-46345fa8b830
* Content: [Best Practices for Secure Planning and Deployment of AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/design/best-practices-for-secure-planning-and-deployment-of-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/design/Best-Practices-for-Secure-Planning-and-Deployment-of-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/design/Best-Practices-for-Secure-Planning-and-Deployment-of-AD-FS.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment] 2022-06-28 23:06
#assign:xelu86

**Comment by Xelu86** [comment] 2022-06-28 23:23
Thanks again for contacting Microsoft. We have reviewed both links provided, "[This](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/design/best-practices-for-secure-planning-and-deployment-of-ad-fs) page" and "this [newer version](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/best-practices-securing-ad-fs)". 

The first link belongs to the "Best Practices for Secure Planning and Deployment of AD FS" of this documentation and the second to "Best practices for securing Active Directory Federation Services". 

Both articles vary greatly on topics discussed and do not appear to be a direct duplicate of older vs newer technologies. Both discuss security within Server AD FS with the distinction of one instructing on hardening your device with greater detail while the other is more in line with the planning and deployment phase.

Thank you.
 
#please-close

**Closed by Xelu86** 2022-06-28 23:23 UTC
Labels: Pri2, windows-server/prod, ad-fs/tech
