### ISSUE TITLE
fix: openSSH setup guide

### ISSUE THREAD

**Issue by profnandaa** [MicrosoftDocs/windowsserverdocs#6999] opened 2023-01-19 12:42 UTC
Ref: https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse?tabs=powershell

I'm getting this weird phenomenon. I wanted to suggest that we do away with the multiple tildes (~), but then it works for `Client` but consistently fails for `Server`, until when I just have one tilde, i.e 

```powershell
Add-WindowsCapability -Online -Name OpenSSH.Server~0.0.1.0
```

I'm not sure about the inconsistencies. Please see my output below:

![image](https://user-images.githubusercontent.com/261265/213445377-27dec8ab-966d-46d6-88eb-8783e164f3f9.png)

**Comment by Xelu86** [comment] 2024-01-16 21:41
Hey @profnandaa,

Thanks again for contacting Microsoft, we value your feedback.

As you stated, _"I wanted to suggest that we do away with the multiple tildes (~)"_. We as writers have zero control of how the product and dev teams decide to produce their apps and software. You can provide them this feedback by using the Windows Feeback Hub.

Working with @christking246, we have set up fresh VMs of the following OSs of different builds (no preview OS release due to their nature):

- Windows 10
- Windows 11
- Windows Server 2019
- Windows Server 2022 

We ran the PS command from this doc as described for both client & server without issue:

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/103963494/6a77fb12-9e9c-4819-902d-5d8f58daa8a5)

There was an exception of WS2019. The 0x800f0950 error was reproduced due to missing cumulative KB update [KB5034127](https://support.microsoft.com/en-us/topic/january-9-2024-kb5034127-os-build-17763-5329-4de58ce5-eb0d-4b9a-95d1-aa15fe30b082) as OpenSSH is directly affected based on the [affected files information](https://download.microsoft.com/download/5/3/8/538ef8b5-2f78-4779-bbb9-c79d52e5965e/5034127.csv) for said update. 

This was not the case reviewing the other OS builds as OpenSSH installed out of the box. We're unable to track what KBs directly affect OpenSSH as it can always change as more cumulative and security updates are released. KB updates are known to potentially affect other aspects of the operating system that, once discovered, are corrected with another KB update. It is recommended to keep your device up to date which may correct such issues.

If you're still having issues, we recommend you reach out to our community forums as this is outside our scope:

- [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home)
- [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home)
- [Microsoft Support Community](https://answers.microsoft.com/)

As there isn't an issue with the doc itself, updates to OpenSSH won't be made and we'll now be closing this thread. Thank you and have a most pleasant day.
#please-close

**Closed by Xelu86** 2024-01-16 21:41 UTC
Labels: Pri3
