### ISSUE TITLE
Wrong command shown

### ISSUE THREAD

**Issue by khadohex** [MicrosoftDocs/windowsserverdocs#4043] opened 2020-03-20 01:50 UTC
Shows "Offline disk" and "Offline volume" instead of "Online disk" and "Online Volume" under both "Syntax" and "Parameters"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d1d8dbb-de9c-a5f0-086b-fe9b5c5cba12
* Version Independent ID: dd471cdd-013d-119d-0aab-2b8eb2b8a355
* Content: [online](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/online#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/online.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/online.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment] 2020-03-20 04:38
Yes, this definitely looks like a copy-paste error from a hasty writing of the document pages.
We should have the following pages linked:
- [**online**](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/online), pointing to
    - [online disk](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/online-disk)
    - [online volume](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/online-volume)
- [**offline**](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/offline), pointing to
    - [offline disk](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/offline-disk)
    - [offline volume](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/offline-volume)

Instead, the online page is currently a duplicate of the offline page, which is both redundant and incorrect.

**Comment by illfated** [comment] 2020-03-20 04:44
(the same hierarchy repeated, but this time with visible links)

- https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/online
    - https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/online-disk
    - https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/online-volume
- https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/offline
    - https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/offline-disk
    - https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/offline-volume

The GitHub page should be quite easy to edit. See the following links to the raw and the normal view:
- https://raw.githubusercontent.com/MicrosoftDocs/windowsserverdocs/master/WindowsServerDocs/administration/windows-commands/online.md
- https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/online.md

**Comment by Xelu86** [comment] 2022-11-02 20:06
#assign:xelu86

**Comment by Xelu86** [comment] 2022-11-02 20:13
Hey @khadohex,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change was made correcting this and this issue was not closed out. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close

**Closed by Xelu86** 2022-11-02 20:13 UTC
Labels: Pri2, windows-server/prod, manage-windows-commands/tech
