### ISSUE TITLE
Configuring the default shell for OpenSSH in Windows

### ISSUE THREAD

**Issue by ackvf** [MicrosoftDocs/windowsserverdocs#3732] opened 2020-01-14 16:11 UTC
https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07417484-bd6d-e6f4-110e-e42c2428a369
* Version Independent ID: 844743a6-f67b-421f-9591-13da36b23b14
* Content: [Installation of OpenSSH For Windows](https://docs.microsoft.com/en-gb/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* GitHub Login: @maertendMSFT

**Comment by dknappettmsft** [comment] 2021-12-08 13:32
Hi, there is not description about what the issue is with this article. I will close this now, but if you want to provide more information later, then please open a new issue. Thank you.

#please-close

**Closed by dknappettmsft** 2021-12-08 13:33 UTC
Labels: Pri2
