### ISSUE TITLE
Reg : Spelling Mistake 

### ISSUE THREAD

**Issue by VIJAY050804** [MicrosoftDocs/windowsserverdocs#4865] opened 2020-10-02 04:27 UTC
Just small Spelling Mistake 
Ref: Azure AD join 

Access Organizational Resource on Mobile device (Phones, **Phablets**) that can't be joined to a Windows Domain, whether they are corp-owned or BYOD 

 https://docs.microsoft.com/en-us/windows-server/identity/whats-new-active-directory-domain-services

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f4538a-b7ae-fd8d-9337-23dffe93c8f8
* Version Independent ID: 0a0a4ea0-8afe-b021-ed19-26e8e720fe8a
* Content: [What's new in Active Directory Domain Services in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/whats-new-active-directory-domain-services)
* Content Source: [WindowsServerDocs/identity/whats-new-active-directory-domain-services.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/whats-new-active-directory-domain-services.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment] 2020-10-02 10:34
Thank you, good catch. I have not heard about that cross between phones and tables yet, but that word would fit the bill if they did. 😄

I will make sure to have that typo corrected. Thank you for the report (and the chuckle it gave me).

**Comment by illfated** [comment] 2020-10-02 10:38
Dang, I must have been sleeping for the last 4 years. The word "phablet" is actually a thing now:
- https://en.wikipedia.org/wiki/Phablet

The real question now is: is this the intended word in this case? It feels like it doesn't, seeing that phones are already mentioned. I would need to check the article to see if this is about phones and phone-sized tablets, and not about full-sized tablets.

**Comment by illfated** [comment] 2020-10-02 10:40
Please note this search result for the word "phablet":
- https://docs.microsoft.com/en-us/search/?terms=phablet

**13 results for "phablet"**

There is quite a real chance that the word "phablet" was intended here.

**Comment by VIJAY050804** [comment] 2020-10-02 10:59
> Dang, I must have been sleeping for the last 4 years. The word "phablet" is actually a thing now:
> 
> * https://en.wikipedia.org/wiki/Phablet
> 
> The real question now is: is this the intended word in this case? It feels like it doesn't, seeing that phones are already mentioned. I would need to check the article to see if this is about phones and phone-sized tablets, and not about full-sized tablets.

Thanks for your swift response. 

I am really sorry, I haven't done cross-check before submitting the document to you.

**Comment by illfated** [comment] 2020-10-02 11:09
> > The real question now is: is this the intended word in this case? It feels like it doesn't, seeing that phones are already mentioned. I would need to check the article to see if this is about phones and phone-sized tablets, and not about full-sized tablets.
> 
> Thanks for your swift response.
> 
You are very welcome. Staying at home with a flu makes it a lot easier to follow up on tickets like this.

> I am really sorry, I haven't done cross-check before submitting the document to you.

No worries, don't be sorry. I was unaware of the new word myself. The word "phablet" was apparently created in 2016, so I have not been aware of it all this time myself. Imagine how old I feel now (or feeling like I have slept under a rock).

By the way, do you think this is enough discussion to conclude the issue and close the ticket? Or would you like to call for some MS Docs team member to weigh in on the vocabulary choices?

**Comment by illfated** [comment] 2020-10-06 02:37
@eross-msft : May I ask for you to check with your team if the word "Phablet" is as common in use as Phone and Tablet, as a new word for "advanced BYOD phone", making this report a moot point, or if your team thinks "Tablet" would be better in this case?

**Comment by VIJAY050804** [comment] 2020-10-06 04:18
Instead of Phablet, most commonly we use the word Tablet or BYOD.

**Comment by illfated** [comment] 2020-10-06 05:34
Fair enough. I will wait for a reply from the MS ServerDocs team before I create a PR to suggest the change.

**Comment by VIJAY050804** [comment] 2020-10-06 05:56
Thanks for swift response :)

**Comment by eross-msft** [comment] 2020-10-06 15:10
@illfated @VIJAY050804   Thank you for checking. We definitely don't recommend using the term, "phablet", I checked all of our terminology guides just to be extra sure. Instead, I would suggest going with "tablet" as you suggested here, especially since the end of the sentence says BYOD.

**Comment by illfated** [comment] 2020-10-06 17:32
Thank you very much. Excellent answer.
That is exactly the kind of decisive answer I was hoping for. 
I will submit a PR to have the word corrected.

**Comment by VIJAY050804** [comment] 2020-10-06 17:44
Dear Team,

Thanks for the reply, I really appreciate it for the quick response and
accepting for  change.

Regards
Vijayanand

**Comment by illfated** [comment] 2020-10-06 18:05
There you go. PR #4889 is ready for review. Feel free to comment or suggest additional improvements.

That PR will automatically close this ticket upon merge.

**Closed** 2020-10-06 18:52 UTC
