### ISSUE TITLE
2 node Pool Quorum

### ISSUE THREAD

**Issue by cedwards-telis** [MicrosoftDocs/windowsserverdocs#2988] opened 2019-06-20 15:40 UTC
I like the clear information in the cluster quorum section, especially detailing how in a 2 node with witness a single node failure is survivable.

In the pool quorum section there are no such examples.  In the table under pool quorum it is indicated that a pool with witness can survive a single node failure.  But what is a pool quorum witness and how is one configured?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88e3efcf-9e4d-e38d-421d-1c47f4f5f375
* Version Independent ID: 2b76919b-96d5-1230-db10-6f8a75a78588
* Content: [Understanding cluster and pool quorum](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/understand-quorum)
* Content Source: [WindowsServerDocs/storage/storage-spaces/understand-quorum.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/understand-quorum.md)
* Product: **windows-server-threshold**
* Technology: **storage-spaces**
* GitHub Login: @adagashe
* Microsoft Alias: **adagashe**

**Comment by MavBoss86** [comment] 2019-07-12 15:51
And let me add one another things: how can we see which is the witness via powershell or gui? And can we change it manually to bring online the cluster? We have build a S2D 2019 cluster and when we shutdown the first node without putting into maintenance (testing a "failure") all the virtual disk S2D goes down. And I think the cause is the witness that is fixed to the first node.

**Comment by BarnumD** [comment] 2019-11-12 15:14
I would also like to find out if multiple witnesses could be used to protect against a witness failure.

**Comment by IngridAtMicrosoft** [comment] 2021-10-16 00:23
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Closed by IngridAtMicrosoft** 2021-10-16 00:23 UTC
Labels: Pri2, windows-server-threshold/prod, storage-spaces/tech
