### ISSUE TITLE
Ubuntu 20.04 LTS support in Hyper-V and documentation

### ISSUE THREAD

**Issue by jaapcrezee** [MicrosoftDocs/windowsserverdocs#4609] opened 2020-07-02 10:39 UTC
Please update information about Ubuntu 20.04 LTS support which is the current LTS release you should use when installing new machines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d52296-198d-7c8a-db99-e8cb336e355f
* Version Independent ID: 77670399-109f-3233-0466-c13d84542039
* Content: [Supported Ubuntu virtual machines on Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-ubuntu-virtual-machines-on-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md)
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @shirgall
* Microsoft Alias: **shirgall**

**Comment by konstruktoid** [comment] 2021-01-04 20:45
Fixed by https://github.com/MicrosoftDocs/windowsserverdocs/commit/fb78b64c3a2ffc434c1e04d16cf7804e9c00df81?

**Comment by konstruktoid** [comment] 2021-01-04 20:47
Duplicate of #4498

**Comment by illfated** [comment] 2021-01-04 21:38
Tagged as duplicate ticket.

#please-close

**Closed by illfated** 2021-01-04 21:38 UTC
Labels: Pri2, compute-hyper-v/tech, windows-server/prod
