### ISSUE TITLE
the guide is unavailable

### ISSUE THREAD

**Issue by Pelago** [MicrosoftDocs/windowsserverdocs#1634] opened 2018-10-11 09:11 UTC
Hi, the link to the "Test Lab Guide: Demonstrate DirectAccess Single Server Setup with Mixed IPv4 and IPv6" is not functioning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c8a4bbf-7d3a-58a5-2480-4f4cbcbc7ddc
* Version Independent ID: 8b20ba72-23fe-eb4a-de0e-03c18866ce65
* Content: [STEP 1 Complete the DirectAccess Configuration](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/directaccess/tlg-multisite/step-1-complete-directaccess-configuration)
* Content Source: [WindowsServerDocs/remote/remote-access/directaccess/tlg-multisite/STEP-1-Complete-DirectAccess-Configuration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/directaccess/tlg-multisite/STEP-1-Complete-DirectAccess-Configuration.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment] 2018-10-22 15:56
@Pelago, try the link again.  I've tested the same link from other documents and it takes me to a download page.  

Closing. Cannot reproduce.

**Comment by Pelago** [comment] 2018-10-22 22:02
it does not still work from Sweden.. i get this message when following the link..
https://go.microsoft.com/fwlink/p/?LinkId=237004

a pritty Picture of an helicopter in Blue and the text

**We're sorry, this download is no longer available.** 
Perhaps one of the following links will help you find what you need. 
Suggested for Windows
Get Windows 10
Get apps for Windows and Windows Phone
Microsoft Update
Suggested for Office
Try Office 365 for free
Buy Office for PC, Mac, and other devices
Download Center
Download Center home
Windows downloads

**Comment by Pelago** [comment] 2018-10-22 22:04
it does not matter if I use EDGE, Chrome, Firefox opera or IE11 browsers...

**Comment by coreyp-at-msft** [comment] 2018-10-22 22:09
Hi @Pelago , can you access this URL?

https://www.microsoft.com/en-us/download/details.aspx?id=29031

**Comment by Pelago** [comment] 2018-10-22 22:10
Yes! thankyou

Patrik Lilja,
CEO


[cid:image005.png@01D46A64.C81A7D00]

________________________________
[cid:image002.jpg@01CE269E.64BDC650]<sip:patrik.lilja@pelam.com>[cid:image003.jpg@01CE269E.64BDC650]<tel:+46706000401>[cid:image004.jpg@01CE269E.64BDC650]<mailto:patrik.lilja@pelam.com>
Pelam Engineering AB, Box 10158, SE43422, Kungsbacka, Sweden. S-board +4630028954
________________________________
This e-mail, including any attached files, may contain confidential and privileged Information for the sole use of the intended recipient(s). Any review, use, by others is strictly prohibited. If you are not the Intended recipient (or authorised to receive information for the recipient), please contact the sender by reply e-mail and delete all copies of this message. Thank you.

**Comment by Pelago** [comment] 2018-10-22 22:12
But that was for server 2012 and I expected 2016
As per info on page https://docs.microsoft.com/en-us/windows-server/remote/remote-access/directaccess/tlg-multisite/step-1-complete-directaccess-configuration



Patrik Lilja,
CEO


[cid:image005.png@01D46A65.15ED4760]

________________________________
[cid:image002.jpg@01CE269E.64BDC650]<sip:patrik.lilja@pelam.com>[cid:image003.jpg@01CE269E.64BDC650]<tel:+46706000401>[cid:image004.jpg@01CE269E.64BDC650]<mailto:patrik.lilja@pelam.com>
Pelam Engineering AB, Box 10158, SE43422, Kungsbacka, Sweden. S-board +4630028954
________________________________
This e-mail, including any attached files, may contain confidential and privileged Information for the sole use of the intended recipient(s). Any review, use, by others is strictly prohibited. If you are not the Intended recipient (or authorised to receive information for the recipient), please contact the sender by reply e-mail and delete all copies of this message. Thank you.

**Comment by shortpatti** [comment] 2018-10-22 22:30
Yes, it works for both 2012 and 2016.

**Closed** 2018-10-22 22:58 UTC
Labels: assigned-to-author, link-issues, networking

**Comment by Pelago** [comment] 2018-10-23 21:59
Thanks!

Patrik Lilja,
