### ISSUE TITLE
The default installation will use an alternative x:\ProgramData\ssh\administrators_authorized_keys for admin users.

### ISSUE THREAD

**Issue by wackydoo** [MicrosoftDocs/windowsserverdocs#1911] opened 2018-11-13 18:41 UTC
The default sshd_config will check an alternative authorized_keys file for users in the Administrators group. You will need to create this x:\ProgramData\ssh\administrators_authorized_keys file and set permissions appropriately (see for example https://docs.microsoft.com/en-us/windows/iot-core/connect-your-device/ssh )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 337c4ea8-1806-92a3-1501-b3ff5dde37bb
* Version Independent ID: c411d389-578d-57c6-cd6e-eaca7f2837db
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* GitHub Login: @maertendMSFT

**Comment by wackydoo** [comment] 2018-11-13 18:44
I just realized that this document is for Windows Server - I was using it to configure the Windows 10 Pro OpenSSH server optional feature, so my comment may or may not be applicable.

**Comment by ikhbarkhan** [comment] 2018-12-12 23:07
# Make sure that the .ssh directory exists in your server's home folder
ssh user1@domain1@contoso.com mkdir C:\users\user1\.ssh\

# Use scp to opy the public key file generated previously to authorized_keys on your server
scp C:\Users\user1\.ssh\id_ed25519.pub user1@domain1@contoso.com:C:\Users\user1\.ssh\authorized_keys

# Appropriately ACL the authorized_keys file on your server  
ssh --% user1@domain1@contoso.com powershell -c $ConfirmPreference = 'None';

**Comment by cniekerk** [comment] 2019-01-02 11:54
In my build of Windows Server 2019 (17763), I am unable to log in using the Administrator account unless if I comment out these two lines in the `C:\ProgramData\ssh\sshd_config` file:

```
Match Group administrators
AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys
```

You might also need to restart the OpenSSH server by executing `Restart-Service sshd` in Powershell after editing the file.

I attempted to create a duplicate of `C:\Users\Administrator\.ssh\authorized_keys` under `C:\ProgramData\ssh\administrators_authorized_keys` but this did not work for me.

**Comment by cniekerk** [comment] 2019-02-04 08:42
@dzmitry-lahoda In order to do that you will probably need to run Powershell as administrator (right click -> Run as administrator) or use the `runas` command to escalate privileges.

**Comment by cniekerk** [comment] 2019-02-04 09:35
@dzmitry-lahoda I have no idea if this will work (don't have a test setup to try it myself right now) but perhaps you could try this?

```powershell
runas /user:administrator "powershell Restart-Service sshd"
```

**Comment by dzmitry-lahoda** [comment] 2019-02-04 09:45
I have put my key into `administrators_authorized_keys`, i did delete key from `authorized_keys`, allowed `Match Group administrators` group and  did restart of `sshd` service on server.  Tried on `ssh` from admin `pwsh` on client and got refusal to connect by credentials. I will try again with steps and recheck. The idea is next - I need my ssh session into remote to be admin to work with services, but I did no achieve that yet. My `ssh` connection is not admin now. I do not want to use windows password into remote each time I want to be admin. May be I can make service work to be lower security work instead of being admin.

**Comment by cniekerk** [comment] 2019-02-04 09:51
@dzmitry-lahoda I do agree with you that this is not convenient but this is also very similar to how things work on *nix systems (login as root not allowed, always login as regular user and use `sudo` to escalate privileges as necessary). I think what Microsoft is trying to do here is in line with what is considered to be best practices.

**Comment by darthwalsh** [comment] 2019-03-20 01:04
If you're having issues or working on fixing documentation or scripts, check out https://stackoverflow.com/q/16212816/771768

**Comment by TheBigBear** [comment] 2021-02-02 10:56
This is a very English centric windows language centric default and FAILS on windows installations other than English. 
They should make it possible, and set it to default, for the group match to check for the Administrators SID instead and not the text string as that can be different depending on the language in use of the windows installation. 

Change the current Match rule to something like this:

```
Match Group *S-1-5-32-544
    AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys
```

This would be a much better and windows language installation agnostic setting and should be the default, not a per language adapted string.

And for the DenyGroups settings this should also be allowing it to be done via SIDs and NOT by text strings that change and vary. 
( also see https://github.com/PowerShell/Win32-OpenSSH/issues/1324#issuecomment-771506890 and https://github.com/PowerShell/Win32-OpenSSH/issues/1581#issuecomment-771512156 )

**Comment by IngridAtMicrosoft** [comment] 2021-10-15 23:52
#please-close

**Closed by IngridAtMicrosoft** 2021-10-15 23:52 UTC
Labels: Pri2
