### ISSUE TITLE
CentOS 7.6.1810 

### ISSUE THREAD

**Issue by jetjo** [MicrosoftDocs/windowsserverdocs#2075] opened 2018-12-12 12:19 UTC
CentOS Linux release 7.6.1810 - Unsupported kernel version after executing install.sh

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 7575f3e6-af25-1cfd-8784-96c72bd94516
* Version Independent ID: 59ea80f9-dbce-1404-ab36-a301175a8c85
* Content: [Supported CentOS and Red Hat Enterprise Linux virtual machines on Hyper-V](https://docs.microsoft.com/ru-ru/windows-server/virtualization/hyper-v/supported-centos-and-red-hat-enterprise-linux-virtual-machines-on-hyper-v#BKMK_7x)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-CentOS-and-Red-Hat-Enterprise-Linux-virtual-machines-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Supported-CentOS-and-Red-Hat-Enterprise-Linux-virtual-machines-on-Hyper-V.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by doctordns** [comment] 2018-12-19 14:47
Which method did you use to install the LIS? Tar files or the ISO?
What kernel do you have on your Linux VM?

**Comment by jetjo** [comment] 2018-12-21 10:01
any methods finisned me to Unsupported kernel version result

**Comment by ephion85** [comment] 2019-11-29 15:23
Used ISO CentOS-7-x86_64-Minimal-1810.iso and LIS 4.3.4-20190818, I uploaded the lis-rpms-4.3.4.x86_64.tar.gz via WinSCP on the guest os and followed the installation stesps described in the PDF, rebooted when prompted, all works as expected

**Comment by illfated** [comment] 2019-12-05 14:41
@ephion85 : Do you consider your issue solved? If yes, please close this issue (if you are able to).

**Comment by HenkPoley** [comment] 2020-05-12 07:41
Same problem on CentOS 7.8.2003 (Core), linux 3.10.0-1127.el7.x86_64, Linux-IC-4.3.5.x86_64.iso

**Comment by illfated** [comment] 2020-05-12 11:36
Although I may agree with your suggestion, please keep in mind that the repository is mainly intended for documentation issues, reporting MS Docs errors or request improvements like document updates for new features and details.

You may want to consider using some form of Feedback Hub reporting to have your suggested changes delivered to the MS developers.

Then again, we can always hope someone in the MS Docs team may have the necessary connections with the developer team to pass this information on to them.

**Comment by DaniHalfin** [comment] 2020-10-28 17:02
@eross-msft can you help with this?

**Comment by illfated** [comment] 2020-10-31 09:00
@konstruktoid : May I ask your opinion on this issue ticket, what would a possible solution look like here?

**Comment by konstruktoid** [comment] 2020-11-02 07:35
Isn't this a duplicate of https://github.com/MicrosoftDocs/windowsserverdocs/issues/638?

**Comment by illfated** [comment] 2020-11-11 00:54
Could be, not sure. Just to see if it is possible to get more feedback, let me ask the following:

Can your issue of unsupported kernel be resolved by the following suggested procedure?

1. Disable automatic updates.
2. Uninstall the LIS downloadable packages.
3. Update the kernel.
4. Reboot.
5. Install the latest LIS release.
6. Reboot again.

**Comment by konstruktoid** [comment] 2020-11-11 11:46
Could solve it, but iirc the issue was that the LIS release didn't sync with the available kernels.

**Comment by illfated** [comment] 2020-11-11 17:54
👍🏻 Thanks for the feedback. Always good to get feedback from those who know more than me. 🙂

**Comment by illfated** [comment] 2020-11-23 20:30
#please-close

**Closed by illfated** 2020-11-23 20:30 UTC
Labels: Pri2, na/svc, windows-server-threshold/prod
