### ISSUE TITLE
Server Performance Advisor download link does not work

### ISSUE THREAD

**Issue by xcabur1** [MicrosoftDocs/windowsserverdocs#4905] opened 2020-10-12 12:33 UTC
Server Performance Advisor download link does not work
https://docs.microsoft.com/en-us/windows-server/administration/server-performance-advisor/microsoft-server-performance-advisor#bkmk-downloadspa

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 697b9e0a-e082-cadd-3c08-ffb54f640e45
* Version Independent ID: 45250bd4-d7e9-6e79-a6d4-80d169cb5ac7
* Content: [Microsoft Server Performance Advisor](https://docs.microsoft.com/en-us/windows-server/administration/server-performance-advisor/microsoft-server-performance-advisor#bkmk-downloadspa)
* Content Source: [WindowsServerDocs/administration/server-performance-advisor/microsoft-server-performance-advisor.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/server-performance-advisor/microsoft-server-performance-advisor.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment] 2020-10-14 23:23
Confirmed. The download links are as follows:
- Microsoft Server Performance Advisor 3.1 (32-bit): https://go.microsoft.com/fwlink/p/?linkid=327751
(points to http://download.microsoft.com/download/0/3/D/03D07D11-18D4-4160-B4AC-915061B85669/SPAPlus_x86.cab)
- Microsoft Server Performance Advisor 3.1 (64-bit): https://go.microsoft.com/fwlink/p/?linkid=327752
(points to http://download.microsoft.com/download/0/3/D/03D07D11-18D4-4160-B4AC-915061B85669/SPAPlus_amd64.cab)

Error message:

![image](https://user-images.githubusercontent.com/38162891/96055607-ccd64b00-0e84-11eb-90a0-4a1d15cb3b70.png)

By the way, I also tested changing the http:// link to https:// - but still the same error page.

**Comment by eross-msft** [comment] 2020-10-15 16:54
@xcabur1 @illfated  I also see the 404 error. I'm looking into this to see if I can find the article owner to provide updated info. I'll let you know if I find out anything.

**Comment by illfated** [comment] 2020-10-15 18:39
Thanks. I don't know if the target files have been removed because of potentially unsafe software due to old and outdated versions, but it is a possible scenario.

Best case scenario would be if there are newer versions of the same files to link to the referred page in question.
Second best option would be if new scripts or methods have replaced the Server Performance Advisor software.

**Comment by eross-msft** [comment] 2020-10-15 18:42
@illfated  Current thoughts are that it was taken down for the same reason dozens of other downloads were taken down in the past year: it used SHA-1 signature, and no owners were around to update it with a modern signature. 

But I'm hoping we can find someone to help us do something about this...

**Comment by illfated** [comment] 2020-10-15 18:50
Thank you for that very useful reminder. I had completely forgotten about it, since my daytime job challenges have occupied most of my thoughts lately.

Anyway, I will be looking forward to more feedback later regarding this content. Thank you for keeping us informed. 👍

**Comment by illfated** [comment] 2021-05-20 19:39
( ref. #5551 )

**Comment by illfated** [comment] 2021-05-20 19:40
@eross-msft : Do you know if anyone new will be assigned to this article & issue ticket?

**Comment by Xelu86** [comment] 2023-03-10 23:48
#assign:xelu86

**Comment by Xelu86** [comment] 2023-03-10 23:52
The microsoft-server-performance-advisor.md article has either been deprecated or absorbed into another article. Closing threads #4905 & #5551 as updates cannot be made.
#please-close

**Closed by Xelu86** 2023-03-10 23:52 UTC
Labels: Pri2, windows-server/prod, administration/tech
