### ISSUE TITLE
Download PDF button doesn't work.

### ISSUE THREAD

**Issue by Trevanoc** [MicrosoftDocs/windowsserverdocs#3878] opened 2020-02-12 19:21 UTC
The button is readable unless downloaded. Once it is, no application (including MS Edge) can read the file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c179cec0-fc0c-2f8e-8b15-cd23b46e58dd
* Version Independent ID: 7d9137c1-5db0-c8ec-419c-ac4540433438
* Content: [if](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/if#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/if.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/if.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment] 2020-04-06 18:51
I think this may be a bug that you (and maybe a minority of others) have experienced. I am unable to reproduce your issue. I use both Google Chrome and Microsoft Edge (chromium-based) (Version 80.0.361.109 (Official build) (64-bit)).

If you really do continue to have this issue, please provide a more detailed step-by-step procedure for how to replicate it.

I suspect that your issue might have something to do with your browser cache and the fact that the PDF in question is 4.84 MB in size (covering the entire [**Windows Commands**](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands) section).

If anything, it would be more proper to report this issue (if it is any MS Docs issue at all) at the top level page https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands .

**Comment by dknappettmsft** [comment] 2022-01-07 18:27
Thanks for the feedback. The 'Download PDF' button is working, so I will close this.

#please-close

**Closed by dknappettmsft** 2022-01-07 18:27 UTC
Labels: Pri2, windows-server/prod, manage-windows-commands/tech
