### ISSUE TITLE
Provide pointer to PowerShell substitute(s)

### ISSUE THREAD

**Issue by arebee** [MicrosoftDocs/windowsserverdocs#3765] opened 2020-01-20 22:02 UTC
The documentation parent page recommends using PowerShell. Would be useful to actually provide links to the PowerShell equivalents. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dfc8030-f3f6-6dae-241c-96104e5d7421
* Version Independent ID: c2857f52-2dea-d007-22d2-6ece7f870f00
* Content: [Netsh commands for interface portproxy](https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-interface-portproxy#feedback)
* Content Source: [WindowsServerDocs/networking/technologies/netsh/netsh-interface-portproxy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/netsh/netsh-interface-portproxy.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by Xelu86** [comment] 2022-07-07 18:19
#assign:xelu86

**Comment by Xelu86** [comment] 2022-07-07 18:47
Thanks again for contacting Microsoft. We value your feedback. The commands in reference to this page, "[netsh-interface-portproxy](https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-interface-portproxy)", work as intended in PowerShell as well. 

The following can be ran in PowerShell as a reference: netsh interface portproxy /?
![image](https://user-images.githubusercontent.com/103963494/177844515-66bef4b4-66b7-4e08-bf5b-650fcd8bbb8a.png)

Adding "add" before the "/?" will provide the following:
![image](https://user-images.githubusercontent.com/103963494/177845366-6447eef1-8cd0-4f0a-9be9-6efa67a411c4.png)

Following the instructions in said document should yield the same results in both Command Prompt & PowerShell.

We will be closing this as resolved. Thank you and have a most pleasant day. #please-close

**Closed by Xelu86** 2022-07-07 18:47 UTC
Labels: Pri2, windows-server/prod, networking/tech
