### ISSUE TITLE
typo in the pre-requisites sections.

### ISSUE THREAD

**Issue by aferrillo** [MicrosoftDocs/windowsserverdocs#1966] opened 2018-11-21 14:25 UTC
The sentences "The following pre-requisites are required for ESL with AD FS 2016." and "The following pre-requisites are required for ESL with AD FS 2019." are still reversed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8634165-2ff5-9b01-e3fc-17827360a5f3
* Version Independent ID: a5a91921-3193-93ad-df22-d486e65b19f8
* Content: [Configure AD FS Extranet Lockout Protection](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-smart-lockout-protection)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment] 2020-10-04 20:41
The page has changed since this ticket was opened. See page history here:
- https://github.com/MicrosoftDocs/windowsserverdocs/commits/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md

The issue is resolved by rewriting several sections in the document.

**Comment by illfated** [comment] 2020-10-04 20:41
#please-close

**Comment by illfated** [comment] 2020-10-31 09:20
#please-close

**Closed by illfated** 2020-10-31 09:20 UTC
Labels: Pri2, windows-server-threshold/prod
