### ISSUE TITLE
Page not found error

### ISSUE THREAD

**Issue by nishantrajmitra** [MicrosoftDocs/windowsserverdocs#4473] opened 2020-06-09 02:05 UTC
[Enter feedback here]
https://docs.microsoft.com/en-us/archive/blogs/clustering/10615526
https://docs.microsoft.com/en-us/archive/blogs/clustering/10614930 

These links are opened with 404 error - Content not found.

Thanks,
Nishant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4150f10d-0ac3-0a70-8bcb-c7c2fa630f66
* Version Independent ID: 41670466-1fa8-d27c-965d-59e3ac362676
* Content: [What's new in Failover Clustering in Windows Server](https://docs.microsoft.com/en-us/windows-server/failover-clustering/whats-new-in-failover-clustering)
* Content Source: [WindowsServerDocs/failover-clustering/whats-new-in-failover-clustering.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/whats-new-in-failover-clustering.md)
* Product: **windows-server**
* Technology: **storage-failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by RAJU2529** [comment] 2020-06-09 13:52
@nishantrajmitra , Thanks for reporting, I checked links, the issue is conformed, i am adding new links now

**Comment by exchange12rocks** [comment] 2020-12-07 16:27
@nishantrajmitra Can you close this issue please, since it has been resolved.

**Closed** 2020-12-08 03:09 UTC
Labels: Pri2, storage-failover-clustering/tech, windows-server/prod

**Comment by nishantrajmitra** [comment] 2020-12-08 03:11
It's done.

Thanks & Regards,
Nishant Kumar
Contact- +91-9972755448
