### ISSUE TITLE
documentation is obsolete

### ISSUE THREAD

**Issue by icegood** [MicrosoftDocs/windowsserverdocs#5229] opened 2021-01-24 14:15 UTC
[Enter feedback here]

Ubuntu has no support of gpg keys via apt-key anymore. 
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25943cc5-9927-5ca7-b9db-4c1d398726c5
* Version Independent ID: ae5bf48b-26cf-b5c8-22c8-68fa9a70258f
* Content: [Linux Software Repository for Microsoft Products](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software)
* Content Source: [WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @victorcheng7
* Microsoft Alias: **vichen**

**Comment by icegood** [comment] 2021-01-24 14:21
Should be smth like 
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/microsoft.gpg add

instead

**Comment by illfated** [comment] 2021-01-24 14:35
cc: @konstruktoid (just in case)

**Comment by konstruktoid** [comment] 2021-01-24 21:25
Will be closed by https://github.com/MicrosoftDocs/windowsserverdocs/pull/5203 and duplicate of https://github.com/MicrosoftDocs/windowsserverdocs/issues/5193

**Comment by illfated** [comment] 2021-01-25 00:06
Thank you very much for confirming. Closing this ticket as a duplicate of #5193 .

#please-close

**Closed by illfated** 2021-01-25 00:06 UTC
Labels: Pri2, administration/tech, windows-server/prod
