### ISSUE TITLE
command "where /r c:\ test" doesn't work

### ISSUE THREAD

**Issue by ardubluesky** [MicrosoftDocs/windowsserverdocs#7660] opened 2024-01-07 17:09 UTC
this command doesn't seem to work in my windows system, and i have no clue why. can someone give a sample on how to use it then?
<img width="654" alt="Screenshot 2024-01-07 223450" src="https://github.com/MicrosoftDocs/windowsserverdocs/assets/64678781/69e9a3b7-bf21-4e83-87f1-b4b02c016342">

**Comment by ardubluesky** [comment] 2024-01-07 17:12
btw, I don't know where this is the correct repository to post this but looking for assistance though. sorry and thanks in advanced. 😊 link: https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/where

**Comment by Xelu86** [comment] 2024-01-09 20:29
Hey @ardubluesky,

The syntax you're using is correct. The issue is that you cannot run this as-is in PowerShell. The `where` command functions natively in the Windows Command Prompt (CMD).

What you're looking for is similar to the command below to accomplish what you desire:

- Get-ChildItem -Recurse -Path "C:\" -Filter "test"

We recommend you look through our [PowerShell Reference](https://learn.microsoft.com/en-us/powershell/scripting/how-to-use-docs?view=powershell-7.4) on available PS cmdlets. We also recommend searching and engaging within our community forums for assistance:

[Microsoft TechNet](https://social.technet.microsoft.com/Forums/home)
[Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home)
[Microsoft Support Community](https://answers.microsoft.com/)

As this is a non-documentation issue, we'll now be closing this thread. Thank you and have a most pleasant day.
#please-close

**Closed by Xelu86** 2024-01-09 20:29 UTC
Labels: Pri3
