### ISSUE TITLE
update - Windows11 - required

### ISSUE THREAD

**Issue by jweidinger** [MicrosoftDocs/windowsserverdocs#6017] opened 2021-11-01 19:22 UTC
Hi, this page is not updated for Windows11.
thank you
jweidinger

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa82e6ef-7f35-9672-2ca3-9006de31b2cf
* Version Independent ID: 1dca040b-d5ba-8449-627b-b3069bd9be0e
* Content: [DirectAccess](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/directaccess/directaccess)
* Content Source: [WindowsServerDocs/remote/remote-access/directaccess/DirectAccess.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/directaccess/DirectAccess.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by ShreyanshTech** [comment] 2022-01-05 08:46
https://youtu.be/s_v2Ury0D6c
Check out my video on Windows 11

**Comment by anaharris-ms** [comment] 2022-11-15 15:09
Duplicate of https://github.com/MicrosoftDocs/windowsserverdocs/issues/6229

**Comment by Xelu86** [comment] 2023-01-17 23:06
#assign:xelu86

**Comment by Xelu86** [comment] 2023-01-17 23:22
Hey @jweidinger,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change was made adding Windows 11 Enterprise as a supported OS for Direct Access. Changes are live. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close

**Closed by Xelu86** 2023-01-17 23:23 UTC
Labels: Pri1, windows-server/prod, remote/tech
