### ISSUE TITLE
How to re-attest 

### ISSUE THREAD

**Issue by stephc-msft** [MicrosoftDocs/windowsserverdocs#3874] opened 2020-02-12 14:26 UTC
If the Hyper-V host changes eg due to firmware updates (and hence shielded VM's wont start as attestation fails), what is the quickest and easiest way to re-attest everything?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e5237ef-7c83-f3cc-ab0e-90acc4e3fdac
* Version Independent ID: fb5b347f-f70b-305f-2cd2-5b0a0501042d
* Content: [Troubleshooting the Host Guardian Service](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-troubleshoot-hosts)
* Content Source: [WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-troubleshoot-hosts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-troubleshoot-hosts.md)
* Product: **windows-server**
* Technology: **security-guarded-fabric**
* GitHub Login: @rpsqrd

**Comment by illfated** [comment] 2020-02-12 21:16
Duplicate of #3873 (same content).

#please-close

**Comment by stephc-msft** [comment] 2020-02-12 22:13
sorry I don’t know how to ‘close’ it

**Comment by illfated** [comment] 2020-02-13 00:32
Fair enough. There is usually a **[Close & comment]** button at the bottom of the issue page, but there might not be one for issue tickets like this when it has been (correctly) created from the docs.microsoft.com page. This only means that we need to wait for a Microsoft Server Docs team member to close it. If so, that is normal and my comment was more directed to a Microsoft Server Docs team member than to you.

**Closed** 2020-02-20 12:44 UTC

**Comment by illfated** [comment] 2020-02-20 21:17
Thank you for closing this ticket. To anyone else who happen to stumble upon this ticket, see #3873 for follow-ups to this issue.
