### ISSUE TITLE
PowerShell cannot run the sc delete command

### ISSUE THREAD

**Issue by tcHylmrX** [MicrosoftDocs/windowsserverdocs#3822] opened 2020-01-30 22:19 UTC
Tried the command in PowerShell in Administrator mode and the service is not removed and no error message returns.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ef8ad4c-710f-4a51-a0ed-cb2245f2051f
* Version Independent ID: b35a40fc-7798-c4ff-226c-20aad279fd39
* Content: [Sc delete](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sc-delete#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/sc-delete.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/sc-delete.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment] 2020-01-31 05:58
Caused by the issue described in ticket #2898 (**Using `sc` in PowerShell has only unintended consequences**).

This ticket page could be a duplicate to the issue ticket linked above.

**Comment by thallam08** [comment] 2020-04-08 01:16
Use "sc.exe" to get Service Control instead of alias

**Comment by illfated** [comment] 2020-04-08 08:27
> Use "sc.exe" to get Service Control instead of alias

Quite so, but also see PR #3952 (**sc and sc.exe on powershell**) to resolve this and issue ticket #2898 (**Using `sc` in PowerShell has only unintended consequences**).

**Comment by skycommand** [comment] 2020-05-06 08:27
Resolved via #4290

**Comment by illfated** [comment] 2020-05-06 14:55
#sign-off

**Comment by illfated** [comment] 2020-07-22 14:39
#please-close

**Comment by illfated** [comment] 2020-11-03 02:34
#please-close

**Closed by illfated** 2020-11-03 02:34 UTC
Labels: Pri2, manage-windows-commands/tech, windows-server/prod
