### ISSUE TITLE
4 Years and still no guidance for License server HA...

### ISSUE THREAD

**Issue by BadgerBadgerAndFox** [MicrosoftDocs/windowsserverdocs#4575] opened 2020-06-22 00:11 UTC
[Enter feedback here]

Why is it that Microsoft has gone through 2000, 2003, 2003 R2, 2008, 2008 R2, 2012, 2012 R2, 2016 and now 2019 and still has yet to produce any guidance around RDS License server HA.
Over the various OS release documentation the closest Microsoft has ever come is the addition on this page that has been 4 years since the last update and still only has a place holder with no link...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60723f7e-747c-1b5c-ad16-7b2382dfe6d0
* Version Independent ID: fba257cf-e827-bf67-4af1-b4676a3a095a
* Content: [Remote Desktop Services - High availability](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-plan-high-availability)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-plan-high-availability.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-plan-high-availability.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment] 2021-11-17 21:45
Duplicate of #4648. Addressed.

**Closed by IngridAtMicrosoft** 2021-11-17 21:45 UTC
Labels: Pri2, windows-server/prod, remote-desktop-services/tech

**Comment by exchange12rocks** [comment] 2021-11-17 22:09
Hi @IngridAtMicrosoft ! Could you please point me to the part of the documentation which addresses this issue? I just do not see it =(

**Comment by IngridAtMicrosoft** [comment] 2021-11-17 22:13
> Hi @IngridAtMicrosoft Ingrid Henkel FTE ! Could you please point me to the part of the documentation which addresses this issue? I just do not see it =(

You will see it sometime this evening, after our next publishing cycle is completed.

**Comment by exchange12rocks** [comment] 2021-11-17 22:16
@IngridAtMicrosoft Ah cool 👍 thank you!
