### ISSUE TITLE
Can't change local language via samsung galaxy tab s7 bookcover keyboard.(remote desktop android app)

### ISSUE THREAD

**Issue by legatalee** [MicrosoftDocs/windowsserverdocs#5647] opened 2021-06-25 06:58 UTC
[Enter feedback here]

I am using ms rd client android application with galaxy tab s7.
I am using galaxy tab book cover keyboard to use remote desktop android application.
But I can't change windows 10 pro's local language via rd client with bookcover keyboard's language change key.
Issue in Korean-English change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e9e26ca-6ca8-4f7f-b033-2398576369af
* Version Independent ID: b5b50e01-baf9-c2fe-7a1e-6f04a276e1fc
* Content: [Get started with the Android client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-android)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-android.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-android.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment] 2023-06-12 16:17
#assign:xelu86

**Comment by Xelu86** [comment] 2023-06-12 16:22
Hey legatalee,

Thanks again for contacting Microsoft. We value your feedback. 

As we understand it, you're describing an issue with the product compared to an issue with the documentation. GitHub isn't quite the right location or channel if searching for technical support, advanced troubleshooting, deeper specifics of the product or feature requests as it is completely outside our scope.

As the issue is quite specific, we recommend that you engage with the product community or seek assistance from our support forums:

- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/
- Microsoft Support: https://support.microsoft.com/ContactUs

Hopefully one of the community experts may be able to better assist. We will now be closing this thread. Thank you and have a most pleasant day. 

#please-close

**Closed by Xelu86** 2023-06-12 16:22 UTC
Labels: Pri1, windows-server/prod, remote-desktop-services/tech
