### ISSUE TITLE
WAC: Errors when connecting to Windows 2008 R2 Server

### ISSUE THREAD

**Issue by kungfoome** [MicrosoftDocs/windowsserverdocs#2442] opened 2019-02-21 07:16 UTC
When trying to connect to a Windows 2008 R2 Server, I get the following errors:

- RemoteException: The property 'Fqdn' cannot be found on this object. Verify that the property exists..
- CPU performance class not found on this machine.

This prevents anything else from loading and it doesn't return anything.

**Comment by kinipradeep** [comment] 2019-02-21 08:52
looks like an issue with perfcounters. Is this a VM on your hypervisor or on the cloud ?
does it boot in safe mode ? 
https://support.microsoft.com/en-in/help/2554336/how-to-manually-rebuild-performance-counters-for-windows-server-2008-6 

some guidance on rebuilding the perf counters ..check if this helps

**Comment by kungfu71186** [comment] 2019-02-21 10:30
@kinipradeep This is a VM on my hypervisor. Initially thats what i thought too, but the counters seem to be working ok. I did try to rebuild them anyway, same issue.

**Comment by kinipradeep** [comment] 2019-02-21 11:12
I am assuming that you are connecting through RDP client and not a piece of code ..
any AV/ Anti malware running especially defender. does it have any impact if turned off. also are specific errors logged in system logs ?

**Comment by kungfu71186** [comment] 2019-02-21 11:14
I believe it may be coming from:

https://github.com/pldmgg/WinAdminCenterPS/blob/fc2f40d5005ff1e2a743abfaffd6fa29e93edd7c/WinAdminCenterPS/WinAdminCenterPS.psm1#L3540

This is also a windows cluster.

**Comment by kinipradeep** [comment] 2019-02-21 11:22
does it have a Heartbeat NIC / IP assigned ? and is this getting registered to DNS ?
or is it a single homed .. are you using host name or the cluster name

**Comment by kungfu71186** [comment] 2019-02-21 11:53
Yes, everything is working as intended. It appears there is no FQDN property for the WMI class MSCluster_CLUSTER.

also, looking at cluswmi.mof, it doesn't appear that there is a property FQDN either. 

Windows 2008 R2:
![image](https://user-images.githubusercontent.com/421589/53167151-363a8380-35e8-11e9-892b-401878d7f55e.png)

Windows 2016 Cluster:
![image](https://user-images.githubusercontent.com/421589/53167175-43f00900-35e8-11e9-9801-c272b3ea23aa.png)

Not sure if this is considered a bug, but everything is working as intended. No errors. This is simply an issue of a property not existing for this class.

**Comment by IngridAtMicrosoft** [comment] 2021-10-16 00:28
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Closed by IngridAtMicrosoft** 2021-10-16 00:28 UTC
Labels: Pri3
