### ISSUE TITLE
The table of return codes seems to wrong.

### ISSUE THREAD

**Issue by jwdonahue** [MicrosoftDocs/windowsserverdocs#587] opened 2018-04-09 23:01 UTC
In a sub-directory with no files, run `xcopy *.txt ..` followed by `echo %errorlevel% and the result is 0, not 1. Run `xcopy somefile.txt ..` and the resulting errorlevel is 4.  This is horribly inconsistent behavior and this document is just wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 544925b9-8587-3e0e-9d49-44b77dbd290d
* Version Independent ID: e9969211-1085-ca1f-afb5-b619edbbfab3
* Content: [xcopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/xcopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/xcopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/xcopy.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by kwbskf** [comment] 2018-12-05 01:12
That particular example is not so bothersome:   when you say *.txt and it matches nothing, you have given it an empty set of files to transfer on the command line, so it has nothing to do; thus a 0 exit code.  But if you give it something to transfer, as with 'somefile.txt', but it does not exist, that is a mis-usage and thus an error.  

Going beyond all that, however, it seems that -1 is not used as an exit code when this description suggests it would be.  Based on this description, I would expect the exit code of 1 when copying contents from an existing directory wherein it ends up finding no files that need to be transferred, perhaps due to some of the options causing existing files to not be included in the transfer.  Yet after trying multiple experiments to see when XCOPY might actually exit with a 1 exit code, I have not been able to make this happen.  Instead, if no files are transferred, but with no error, I always get exit code of 0.

Thus, I can agree that something is amiss here.

**Comment by jwdonahue** [comment] 2018-12-05 19:04
If were 'xcopyifexist', then maybe zero files copied would be acceptable. In this case, I am telling xcopy, there's files with this extension here, copy them. If they don't exist that should be some kind of error in my opinion.

**Comment by kairavb** [comment] 2019-02-19 05:11
hey, i want to past the input of a variable in the command xcopy
like this:-
 @echo off
set /p sr=source?

set /p lo=location?

xcopy " pasting the entered value of variable sr  "  " pasting the entered value of variable lo"

echo %username%
pause
but i don't know how to do it.

**Comment by kwbskf** [comment] 2019-03-27 23:15
Wow!  Closed with no description of why.  I'm surprised that's even allowed by the system.  Certainly, that behavior is not helpful.  There was no argument even presented here to suggest that the original submission was in error, or that the problem is not really a problem, or even to say that there is a reason for not doing anything about it.  I find that rather disturbing.

**Comment by daveba** [comment] 2019-03-27 23:18
Hello @kwbskf, thanks for the follow-up.  We will create a backlog item for this issue.  I will reopen so that it can be tracked.  Thanks!

**Closed** 2020-10-28 17:10 UTC
Labels: Pri2, unspecified/svc, windows-commands

**Comment by jwdonahue** [comment] 2020-10-28 19:27
@huypub's pull request seems to have erroneously linked to this issue thread.
