### ISSUE TITLE
Technical accuracy of what Event ID 1201 is about

### ISSUE THREAD

**Issue by aut0pil0t** [MicrosoftDocs/windowsserverdocs#5852] opened 2021-09-05 08:47 UTC
Hello,

Just want clarify the technical accuracy of Event ID 1201 as AD FS does not seem to log it when there is an account lockout as stated in this document. Event ID 1201 is logged for Application Token Failures. https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging also states that Event ID 1201 is about Application Token Failures, not lockouts, which is actually true when we look at the Event Logs.

On the other hand, Event ID 1210 is logged to indicate a lockout. So, it seems like there is perhaps a typo and 12**01** should be 12**10**. Please validate.

Thanks,
Nimantha

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0238d6f-4073-172e-de62-e2d973d993b7
* Version Independent ID: 3789bcce-bebd-8a9d-c814-45ce6c1bfe47
* Content: [Configure AD FS Extranet Smart Lockout Protection](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-smart-lockout-protection)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by robinharwood** [comment] 2022-04-13 10:35
#assign:robinharwood

Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made, although there have been further updates with subsequent releases which supersede the updates in your issue. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by aut0pil0t** [comment] 2022-04-13 11:58
This is still indeed an issue because the issue I raised was not rectified. The explanation of Event ID 1201 described here is not actually true when it comes to actual logs on Windows Server. It is still technically inaccurate.
________________________________

**Comment by PRMerger15** [comment] 2022-04-13 11:58
Only Microsoft employees can close issues or pull requests via commenting in this repo.

**Comment by PRMerger16** [comment] 2022-04-13 11:58
Only Microsoft employees can manage issues via commenting in this repo.

**Comment by robinharwood** [comment] 2022-04-13 12:35
Hi Nimantha,

Apologies, I see the error in my closure. I was looking doc details, content source section but that doesn't appear to be the article you are reference. Just to confirm the issue is with the [AD FS Troubleshooting - Events and Logging](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging) article, not the [Configure AD FS Extranet Lockout Protection](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-soft-lockout-protection) article in the content source?

Thanks,
Robin

#please-open

**Comment by aut0pil0t** [comment] 2022-04-14 17:10
Hi Robin,

No, that's incorrect. I'm referring to the same article that I have stated originally, specifically the section https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-smart-lockout-protection#ad-fs-extranet-smart-lockout-events

**Comment by robinharwood** [comment] 2022-04-14 20:23
Thanks for clarifying Nimantha, leave it with me and I will look into this.

**Comment by Xelu86** [comment] 2022-11-07 23:10
#assign:xelu86

**Comment by Xelu86** [comment] 2022-11-08 00:45
Hey @aut0pil0t,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting this Event ID and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close

**Closed by Xelu86** 2022-11-08 00:45 UTC
Labels: Pri2, windows-server/prod, ad-fs/tech
