### ISSUE TITLE
Azure AD as a prerequisite?

### ISSUE THREAD

**Issue by johnharvieux** [MicrosoftDocs/windowsserverdocs#599] opened 2018-04-11 14:37 UTC
The prerequisites list an Azure AD subscription.  Why is this necessary for ADFS authentication?

**Comment by thibaultchatiron** [comment] 2018-04-11 17:39
This is not necessary. Maybe a mistake because the given example is based on the Azure AD Sample...

**Comment by lizap** [comment] 2018-04-11 17:49
This issue is a duplicate of https://github.com/MicrosoftDocs/windowsserverdocs/issues/600, so I'm going to close this one. Thanks!

**Closed by lizap** 2018-04-11 17:49 UTC
