### ISSUE TITLE
Additional info required

### ISSUE THREAD

**Issue by Ron-ski** [MicrosoftDocs/windowsserverdocs#5650] opened 2021-06-27 08:41 UTC
I found this guide very useful, but it only helped with half the problem.

I setup the external switch but still had no network access when I set the VM to use an address on the local subnet.

I eventually found that you have to tell the VM to use the external switch, rather than the default switch, simple enough once I figured it out.

So it would be worth mentioning this in the guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e6f2ad2-2525-dd4f-3e58-3afdf032fd47
* Version Independent ID: 71ba6edc-2be3-ce8f-2930-afa5bf5d61e9
* Content: [Create a virtual switch for Hyper-V virtual machines](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/get-started/create-a-virtual-switch-for-hyper-v-virtual-machines)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/get-started/Create-a-virtual-switch-for-Hyper-V-virtual-machines.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/get-started/Create-a-virtual-switch-for-Hyper-V-virtual-machines.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by Xelu86** [comment] 2023-09-06 19:56
#assign:xelu86

**Comment by Xelu86** [comment] 2023-09-06 19:56
Hey Ron-ski,

Thanks again for contacting Microsoft. We value your feedback. 

Glad to hear you resolved your issue. This documentation is a basic step-by-step guide on creating a virtual switch. If a user elects to use an external switch, for whichever scenario that requires it, you must also change your Network Adapter settings in Hyper-V to use the appropriate network in order for it to function as intended.

We cannot document every user-case scenario in our documentation. We do have other channels for such scenarios or if more technical help is needed:

- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).

As this is a non-documentation issue, we’re closing this thread.

Thank you and have a most pleasant day. 
#please-close

**Closed by Xelu86** 2023-09-06 19:56 UTC
Labels: Pri1, windows-server/prod, hyper-v/tech
