### ISSUE TITLE
The top infrastructure diagram is hard to read in dark mode. 

### ISSUE THREAD

**Issue by undevin** [MicrosoftDocs/windowsserverdocs#5094] opened 2020-12-08 21:23 UTC
The top infrastructure diagram on this page is really hard to read in dark mode. I tested out the page in MS Edge, Chrome, Firefox, and Safari. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74d09c81-d205-dbd0-ea6a-aaf469eadf5c
* Version Independent ID: 458db848-1b30-1115-8814-3a639a57c70b
* Content: [Configure Device-based Conditional Access on-Premises](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-device-based-conditional-access-on-premises#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-Device-Based-Conditional-Access-on-Premises.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-Device-Based-Conditional-Access-on-Premises.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment] 2020-12-09 15:41
I can confirm this. The text description for each of the individual diagram figures tend to blend in with a dark background, making them less visible. Most of the figure texts inside the image is adapted to a white or very light (as opposed to dark) background.

A possible solution would be to capture some white background only for the text within image, to make the texts more readable in Dark mode / High contrast mode.

**Comment by PRMerger5** [comment] 2021-10-21 20:59
The following users don't have valid GitHub IDs, or are not collaborators on this repo: ingridatmicrosoft 
gh issue comment 5077 -b ingridatmicrosoft

**Comment by billmath** [comment] 2023-07-14 17:35
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close

**Closed by billmath** 2023-07-14 17:35 UTC
Labels: Pri2, windows-server/prod, ad-fs/tech
