### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by JozoSlejko** [MicrosoftDocs/windowsserverdocs#3958] opened 2020-02-26 19:01 UTC
"Azure Extended Network" link points to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c8fa86e-65b1-d8d1-c1e6-d7ba721d7f75
* Version Independent ID: 714b296f-07d4-3e09-3928-483e9069d180
* Content: [Connecting Windows Server to Azure hybrid services](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/azure/#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/azure/index.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/azure/index.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment] 2020-02-27 18:18
All 3 links named "Azure Extended Network" on the page https://docs.microsoft.com/windows-server/manage/windows-admin-center/azure/ :
- https://go.microsoft.com/fwlink/?linkid=2109517&clcid=0x409

It points directly back to the same page, https://docs.microsoft.com/windows-server/manage/windows-admin-center/azure/ .
***
The only site:microsoft.com web search page related to this (besides this page itself) is the following TechCommunity page:
- https://techcommunity.microsoft.com/t5/windows-admin-center-blog/what-s-new-in-windows-admin-center-1910/ba-p/977028

***
I am uncertain where to go from here, whether the fwlink was intended to go to a specific page section, a different page or to do something else.

**Comment by illfated** [comment] 2020-10-31 01:14
This referenced page still needs to have its "Azure Extended Network" URL (x3) updated from the existing one, which is still pointing to itself.

**Comment by illfated** [comment] 2020-10-31 09:48
See issue ticket #4749 (**Wrong Link?**) and PR #4752 **WAC/Azure Extended Network: replace recursive URL** to resolve this issue.

**Comment by illfated** [comment] 2020-11-13 00:21
Issue resolved in PR #4752 / commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/01b3140f79f5614ce566e8036474feefafbeddc3 .

**Comment by illfated** [comment] 2020-11-13 00:22
#please-close

**Closed by illfated** 2020-11-13 00:22 UTC
Labels: Pri2, manage/tech, windows-server/prod
