### ISSUE TITLE
netsh page recommends powershell, but provides no links to alternatives

### ISSUE THREAD

**Issue by MartinSGill** [MicrosoftDocs/windowsserverdocs#4496] opened 2020-06-12 13:48 UTC
The document says this:

>  Important
>
> It is recommended that you use Windows PowerShell to manage networking technologies in Windows Server 2016 and Windows 10 rather than Network Shell. Network Shell is included for compatibility with your scripts, however, and its use is supported.

But does not provide links to the powershell alternatives that should be used.

For example, what is the powershell equivalent of `netsh http add/show urlacl` ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdf15d6d-c63e-6ec4-d1c0-bb800eec7f12
* Version Independent ID: 595b6b57-f169-e38d-35d7-91eaa3b33610
* Content: [Network Shell (Netsh)](https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh)
* Content Source: [WindowsServerDocs/networking/technologies/netsh/netsh.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/netsh/netsh.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by amadbear** [comment] 2021-07-08 15:01
Hmmm...what's that?...yup...do you hear it also?....yup, still hearing crickets! Jokes aside, anybody got feedback on the @MartinSGill  example, powershell equivalent netsh http add urlacl for powershell?

**Comment by IngridAtMicrosoft** [comment] 2021-10-18 23:16
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment] 2022-07-12 20:58
#assign:xelu86

**Comment by Xelu86** [comment] 2022-07-13 01:18
Thanks again for contacting Microsoft. We value your feedback. The commands in reference to this page, "[netsh](https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh)", work as intended in PowerShell as well. [Here](https://docs.microsoft.com/en-us/windows/win32/http/add-urlacl) is a guide to the commands in question with a few examples.

The following can be ran in PowerShell as a reference respectively: "netsh http add" and "netsh http show"
![image](https://user-images.githubusercontent.com/103963494/178597475-5fa52adb-d5c0-455c-8122-6a9bb3017725.png)

Here is an example of urlacl in use:
![image](https://user-images.githubusercontent.com/103963494/178626720-a9b61604-d543-49cc-8ab8-c2aa5d524f80.png)

To know what your SDDL string is, you can run the following command in PowerShell: get-acl c:\windows | fl

To learn more about these commands, you can follow the articles below:

- [add urlacl](https://docs.microsoft.com/en-us/windows/win32/http/add-urlacl)
- [SDDL String Format](https://docs.microsoft.com/en-us/windows/win32/secauthz/security-descriptor-string-format)

Following the instructions in said document should yield the same results in both Command Prompt & PowerShell.

We will be closing this as resolved. Thank you and have a most pleasant day. #please-close

**Closed by Xelu86** 2022-07-13 01:18 UTC
Labels: Pri2, windows-server/prod, networking/tech

**Comment by MartinSGill** [comment] 2022-07-14 07:55
> The commands in reference to this page, "[netsh](https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh)", work as intended in PowerShell as well.

That does not address the original issue. I already know how to use netsh!

The page says **recommend using powershell**. Since Microsoft recommends that I use powershell, I would like a link to the powershell equivilant command, so that I can follow the advice provided to stop using netsh, and use powershell instead.

Telling me how to use netsh from powershell, is not the same as telling me how to use powershell **instead of** netsh.

If it cannot be done in powershell, then stop recommending powershell!

**Comment by Xelu86** [comment] 2022-07-15 03:18
Hello @MartinSGill,

I may have misunderstood your initial question. There are several commands in PowerShell that are equivalent to netsh. Please see this link for the cmdlets: https://docs.microsoft.com/en-us/powershell/windows/get-started?view=windowsserver2022-ps

Click on "Reference" to expand the cmdlets:

![image](https://user-images.githubusercontent.com/103963494/179089794-e4c04b18-33df-428b-b08d-ffd1a3dbd431.png)

There are several commands to perform different functions in their own categories. As this deals with networking in general, they would be the ones to review but may fall under different cmdlets:

![image](https://user-images.githubusercontent.com/103963494/179089723-1ab56c7a-b464-4fc6-b58c-94a7b8300aca.png)

I am aware that this isn't an apples to apples list of equivalents, as seen in the short example below, but I am unaware and have not heard of a full list of equivalents existing in this fashion for PowerShell integration.

- netsh interface show interface > Get-NetworkAdapter | format-table
- netsh interface set interface Wi-Fi disable > Disable-NetAdapter -Name <name> -Confirm:$false
- netsh advfirewall show all > Get-NetFirewallProfile
- netsh interface ipv4 show config > Get-NetIPConfiguration

For the specific command in question, netsh http add/show urlacl, I am having difficulty locating the PowerShell equivalent in our database. Doing some digging led me to an external module named Carbon, not made nor supported by Microsoft, that offers this command and others.

![image](https://user-images.githubusercontent.com/103963494/179099795-e4116d3c-cb62-4911-b066-1977ca148cc6.png)

[Here](https://github.com/webmd-health-services/Carbon/releases) is the link to the Dev(s) GitHub release page.
[Here](http://get-carbon.org/) is their website (doesn't seem to be updated/maintained).

I don't know how much support is involved with these modules as per their creator(s), it is "as-is". I am sorry we don't have a full conversion list compiled somewhere and hope that this is a more favorable answer than prior.

Thank you kindly.

**Comment by MartinSGill** [comment] 2022-07-19 06:23
@Xelu86 

My initial post was that the documentation was incomplete/inaccurate.

If you tell someone not to use a tool (they've just opened the help page for) but to use another tool instead, then you should at a minimum link to the equivalent commands for that preferred tool.

If there are no equivalent commands, then you shouldn't be recommending people to use a tool that doesn't actually do what they need to do.

**Comment by ariehm-gd** [comment] 2024-07-10 20:16
did we ever determine whether there is an actual, first-party powershell equivalent to "netsh http add urlacl"?

i know that some netsh commands have been replaced with more modern powershell-y cmdlets -- for example, `netsh http add sslcert` can now be accomplished with `Add-NetIPHttpsCertBinding`. but still, now, in 2024, i cannot find a microsoft-official powershell cmdlet that adds url reservations.
