### ISSUE TITLE
Is the SPN for ADFS host/ or http/?

### ISSUE THREAD

**Issue by Taomyn** [MicrosoftDocs/windowsserverdocs#5039] opened 2020-11-20 08:18 UTC
Is the SPN for ADFS host/ or http/ because most other places including MS documents show it as host/ ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cae6d9d8-4a22-f41e-a43f-b88816ae4519
* Version Independent ID: aad0e220-49d9-b9bc-10b7-ea0155af1d96
* Content: [AD FS Troubleshooting - Integrated Windows Authentication](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-iwa)
* Content Source: [WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-iwa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-iwa.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by exchange12rocks** [comment] 2020-12-06 15:05
Basically, it's a duplicate of #4922

**Comment by illfated** [comment] 2020-12-09 21:09
Duplicate of #4922 — please add comments and suggestions to that ticket.

#please-close

**Closed by illfated** 2020-12-09 21:09 UTC
Labels: ad-fs/tech, windows-server/prod
