### ISSUE TITLE
storage migration service re-sync changed files to destination server

### ISSUE THREAD

**Issue by JNDDaniel** [MicrosoftDocs/windowsserverdocs#2437] opened 2019-02-20 04:12 UTC
Commenting after some playing with SMS. 
After 7 days of waiting for the migration of our 08R2 file server, it all seemed to work well, and as described.
My issue at the moment is the changed files on the source server that occur over the full week migration that i need to be able to re-sync to the destination server so that the latest files are all migrated.
I'm not able to find a way in the SMS job that allows me to update/re-sync changed files after cut over. i thought that maybe i'm going to be forced to have a robocopy script prepared to run after the SMS tool, but seems like a function of SMS that would be fairly necessary for most people?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c3b0886-820a-0b3c-8382-8d65fc8c3b27
* Version Independent ID: 3e310218-abc0-5249-bb16-7c21402e32c0
* Content: [Storage Migration Service overview](https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/overview)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-migration-service/overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by jte369** [comment] 2019-05-08 16:06
Choosing to Start Transfer will do the incremental sync.  You may get a warning that this will start the transfer all over again, but this is a bug.  From my testing, it does actually do an incremental transfer, after the first time it runs.

**Comment by slomond** [comment] 2019-05-14 23:55
In our testing it seems to transfer all the file again.. Each time we run a start transfer it takes a similar amount of time.. I would really like it to be able to just do the changed files like you can do with robocopy.

**Comment by jte369** [comment] 2019-05-17 15:10
![IncrementalTransfer](https://user-images.githubusercontent.com/50378149/57937563-2901fd80-7894-11e9-8486-4e65db834237.PNG)
Took a screenshot with server name redacted, to show that we are getting incremental transfers, as mentioned in my previous comment.

**Comment by slomond** [comment] 2019-05-17 15:53
I too am seeing that but it takes the same amount of time to complete original transfer vs incremental.. So I think it is doing all the copying the second time just noting the number of newer files.. In my last case it was a couple hundred file few hundred megs in size and it took 5 hours to copy.. Same as the original transfer time of 500+ gigs..

**Comment by nedpyle** [comment] 2019-05-21 22:01
Are you seeing in the CSV transfer details log that it actually copies the files again? SMS does differential transfers unless told not to, so if it is taking the same amount of time or transferring files when you told it not to, please open a support case so we can investigate.

**Comment by jte369** [comment] 2019-05-22 21:04
I agree with slomond that the "incremental" copy is crazy slow.  I got frustrated and went back to Robocopy for my transfer, and I just did in 12 minutes with Robocopy what was taking 9-10 hours with the tool.  I never got the CSV logs to work.  I think this tool has tremendous potential, but I'm going to wait for it to mature some before I try again.

**Comment by nedpyle** [comment] 2019-05-22 21:23
Hi. If you don't work with us through a support case, it may not improve when can't reproduce this issue. If the issue is a bug the case won't cost anything. We can also figure out why CSV downloads were not working for you.

Robocopy doesn't copy with our level of fidelity - you will not be retaining all aspects of files compared to SMS's existing or coming features, such as local security. We made SMS for a reason.

**Comment by JNDDaniel** [comment] 2019-05-22 21:30
I would also have to test this again at some stage. I have not done any further testing since i spent a week or so playing with it before i posted the original thread.

DK.

Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by nedpyle** [comment] 2019-05-22 21:33
I 100% appreciate any feedback you all give. We'll be looking into this from our end as well. We update SMS frequently, a great big set of fixes and new features comes out in the next month or two.

**Comment by slomond** [comment] 2019-05-23 09:11
We are in the process of using SMS to migrate a few servers.. I will complete more testing once we have our next migration server in place.

**Comment by slomond** [comment] 2019-06-03 11:40
Ok we have a couple of servers in progress now and I am no longer seeing the long transfer time on the  incremental..  We are using SMS version 1.25.0 and Windows Admin Center version 1904..

**Comment by nedpyle** [comment] 2019-06-03 21:47
Thanks for the heads up. We're looking into some good optimizations to add here for incremental perf, nonetheless. Thanks for keeping on us. :)

**Comment by sbelongie** [comment] 2019-06-11 13:22
Just wondering what the expected release schedule for this could be.  It would be helpful in planning our cut over.

**Comment by nedpyle** [comment] 2019-06-11 16:37
Not sure, but it won't require a full release of Windows Server, so not years. We are about to release a huge number of new features and fixes under a cumulative update, for instance - support clusters, Samba sources, Azure IaaS direct destinations, etc. We'd do something similar for this bunch of improvements once they are nailed down.

**Comment by Chrisnet46** [comment] 2019-12-03 11:23
I've got a very slow differential transfer time. I opened a support ticket with Microsoft and the support engineer confirmed it was a known issue. Now, I am wondering if I still can use this tool in production (slow differential transfer time aside) or is there any other hiding issues that can compromise our file server migration.

**Comment by nedpyle** [comment] 2019-12-03 21:55
Have you installed at least September (ideally November, KB4523205) monthly cumulative update on your orchestrator and any WS2019 destinations?

As far as the other concern, SMS is fully supported in production. We do not "hide issues."

**Comment by Chrisnet46** [comment] 2019-12-05 13:48
Hi Ned, 

The Microsoft support engineer told me that the performance issue I encountered was a known issue and it is not listed here https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/known-issues, that's why I spoke about "an hidden known issue".

So today, I installed the last cumulative update on the Orchestrator and destination server, add a FileTransferThreadCount to 64, it improves the differential transfert speed significantly. 

A few questions though :
1 -  In the transfer log, I can see a lot of directories (maybe all) listed with the LastTransferIntent showing "Modify", is it normal ? Aren't they copied again since they are detected "modify"

here is an excerpt of the transfer log:
 FilerMigrate	xxxx.xxxx.xx	archives	D:\Deploy\Dell\GPO\STARTUP_WOL\archives	Directory	0	Directory	08/08/2017 08:44:02	14/11/2017 14:23:42	14/11/2017 15:23:42	S-1-5-32-544	O:BAG:DUD:(A;OICIID;FA;;;SY)(A;OICIID;FA;;;BA)(A;OICIID;0x1200a9;;;AU)	0		False	Modify

2 - The last differential transfer I ran, count more processed files (664 137) than source files (668 264),  strange, no ?

3 - Last question : when I select the source shared folder to be include, do I need to select the root administrative share and the shared subfolders I want to migrate or selecting the administrative share only will be enough and will include the shared subfolders with the right permissions?

Thank you for your help

**Comment by nedpyle** [comment] 2019-12-05 21:36
No worries. I made sure to update our Known Issues page with a very explicit message, it should be public soon. Glad to hear the transfer was better; we have another improvement ready there, how to have it out after the new year.

1. We don't actually 'transfer' folders, they are volume metadata we recreate or modify as needed. So they log kinda weirdly and mainly should just be ignored in the logs, tbh.

2. If we had to delete some files from the destination to mirror the source on a retransfer, or if files were deleted since the last transfer, we can end up with some oddities like this that won't be totally understandable at a glance. I will update our FAQ to explain this better.

3. If you select the Administrative Shares option to you are deciding too migrate the entire volumes. Checking and unchecking admin shares (D$) on those volumes will allow you to opt out of the whole volume and just follow and custom shares on that volume. Leaving the admin share checked and unchecking custom shares on that volume will mean all data transfers, but we won't recreate those shares you unchecked. 

No problem

**Comment by Chrisnet46** [comment] 2019-12-06 16:39
Hi Ned,
Ok, still testing...
I launched successive differential transfers. For each transfer, the transfer details shows always nearly 20 GB of new files. I am sure, there is no 20 GB of new files between successive transfer. 

If I open the transfer log and do some filtering , I have :
files/create : 27 MB
files/modify 21 GB

So it looks like the 20 GB detected new files are modified files. But they were not modified between each transfer. Here is an excerpt of the transfer log for one of this file :

D:\XXXX\XXX.bak	File	8390815744	Archive	06/12/2019 01:08:01	06/12/2019 13:51:37	06/12/2019 01:09:44	S-1-5-21-1123561945-1425521274-725345543-5363	O:S-1-5-21-1123561945-1425521274-725345543-5363G:DCD:(A;ID;0x1301bf;;;S-1-5-21-1123561945-1425521274-725345543-5363)(A;ID;FA;;;SY)(A;ID;FA;;;S-1-5-21-1123561945-1425521274-725345543-1449)(A;ID;FA;;;BA)	0	System.Byte[]	False	Modify

Do you have an explanation.

Thank you

**Comment by nedpyle** [comment] 2019-12-06 23:40
Can you send me that that log line above for that exact same file when you have run _one more_ retransfer? Or any file, as long as it claimed to be transferred both times - I need to see two log entries for the same exact file. We want to see if metadata is changing or if we have a bug.

**Comment by Chrisnet46** [comment] 2019-12-10 09:14
Attached excerpt from two consecutive differential transfers I ran yesterday.
[SMS compare pass3.xlsx](https://github.com/MicrosoftDocs/windowsserverdocs/files/3943943/SMS.compare.pass3.xlsx)

**Comment by nedpyle** [comment] 2019-12-11 02:34
Thanks very much, get back to you in a bit

**Comment by ITMHelps** [comment] 2019-12-22 02:47
The Start Transfer button does not do a delta copy, it starts the process from scratch and copies the existing files (that it just moved to the destination) to a folder.  I've tried this twice now.  Move over 1,000,000 files and it fails on 16 (because they are in use) and rather than give me the option to retry/delta copy I have to format the destination volume and start all over.

![image](https://user-images.githubusercontent.com/42219953/71316279-10b21c80-243b-11ea-976d-31d7466a249c.png)


![image](https://user-images.githubusercontent.com/42219953/71316304-861ded00-243b-11ea-9216-14105db2294a.png)

**Comment by IngridAtMicrosoft** [comment] 2021-10-16 00:28
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Closed by IngridAtMicrosoft** 2021-10-16 00:29 UTC
Labels: Pri2, windows-server-threshold/prod

**Comment by sanglyb** [comment] 2021-10-30 11:09
We have the same issue. 
We have to migrate big file server (about 20TB of data), and resyncing takes huge ammount of time. 
For initial transfer it took about 3-4 days, and for resync - 2-3 days. Not sure that files are recreating, but I think that it should take much faster for resync...

**Comment by IngridAtMicrosoft** [comment] 2021-11-01 16:02
@sanglyb This issue for Documentation has been closed. If you have suggestions for improving this document, please open a new GitHub issue.  If you need assistance with your implementation, please contact support.
