### ISSUE TITLE
"are you sure ???" 

### ISSUE THREAD

**Issue by Merola132** [MicrosoftDocs/windowsserverdocs#4470] opened 2020-06-08 18:26 UTC
There is a "are you sure ???" after the Database (Global Catalog) | 8.5 GB recommendation.

Was that supposed to be there?

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14876129-a683-ad93-6043-26fc6afdb456
* Version Independent ID: 041a6bb3-27cc-dd06-fc45-2f34bb466fc8
* Content: [Capacity planning for Active Directory Domain Services](https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/role/active-directory-server/capacity-planning-for-active-directory-domain-services)
* Content Source: [WindowsServerDocs/administration/performance-tuning/role/active-directory-server/capacity-planning-for-active-directory-domain-services.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/performance-tuning/role/active-directory-server/capacity-planning-for-active-directory-domain-services.md)
* Product: **windows-server**
* Technology: **performance-tuning-guide**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea; kenbrunf**

**Comment by illfated** [comment] 2020-06-08 19:41
See issue ticket #4339 (which your ticket is a duplicate of) for more information.
(The original issue ticket source in the German page: https://github.com/MicrosoftDocs/windowsserverdocs.de-de/issues/21).
You might want to close this ticket and comment in #4339 .

**Closed** 2020-06-15 18:55 UTC
