### ISSUE TITLE
Windows versions listed for /p are out of date

### ISSUE THREAD

**Issue by KitPatterson** [MicrosoftDocs/windowsserverdocs#4101] opened 2020-03-31 16:21 UTC
"The /p parameter is only supported on the route command for Windows NT 4.0, Windows 2000, Windows Millennium edition, Windows XP, and Windows Server 2003."
Presumably this should be extended with modern Windows versions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5298689-e441-3788-b31d-967dbce4f735
* Version Independent ID: 5b078c74-5b82-3b35-5842-8ce6142b2152
* Content: [route_ws2008](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/route_ws2008#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/route_ws2008.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/route_ws2008.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment] 2020-04-03 19:42
Fair point. I would like to add that the page itself is oddly titled **route_ws2008** in addition to the file name being the same. It looks to me as if the file name & page title should simply be **route** -- but I suppose it would be quite useful to have this confirmed by the document author or current maintainer / manager before proposing this type of change.

As you said, it is somewhat odd that the /p parameter description lists all those unsupported versions, as long as the page itself states:
> Applies To: Windows Server (Semi-Annual Channel), Windows Server 2016, Windows Server 2012 R2, Windows Server 2012

@coreyp-at-msft : Are you available for comment regarding this page and any potential suggestions via PR to update this page?

**Comment by Xelu86** [comment] 2022-10-31 20:50
#assign:xelu86

**Comment by Xelu86** [comment] 2022-10-31 20:53
Hey @KitPatterson,

Thanks again for contacting Microsoft. We value your feedback. 

Since the opening of this GitHub issue, it appears the documentation has been updated and this case has not been closed. Updates are live and we will now be closing this thread. 

Thank you and have a most pleasant day. #please-close

**Closed by Xelu86** 2022-10-31 20:53 UTC
Labels: Pri2, windows-server/prod, manage-windows-commands/tech
