### ISSUE TITLE
Dead link to static IP address section

### ISSUE THREAD

**Issue by KidElectric** [MicrosoftDocs/windowsserverdocs#4639] opened 2020-07-15 17:19 UTC
title says it all
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb3496f-9df6-8859-4569-ea033daed5ac
* Version Independent ID: 9f762b67-575d-ea11-08d5-edbab9a21f15
* Content: [Remote Desktop - Allow access to your PC from outside your network](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-allow-outside-access)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-outside-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-outside-access.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **elizapo**

**Comment by RAJU2529** [comment] 2020-07-15 19:08
@KidElectric. issue is conformed by me also after checking the link.

**Comment by illfated** [comment] 2020-07-15 20:32
<details>

@RAJU2529 : I think you mean **confirmed** with the letter **i** , instead of "conformed" (which means to comply with, align with or adapt to).

**Comment by illfated** [comment] 2020-07-15 20:42
- Archived page from 2019-04-11:
https://web.archive.org/web/20190411124602/https://docs.microsoft.com/en-us/windows-hardware/customize/mobile/mcsf/enable-static-ip
- Archived page from 2019-08-15:
https://web.archive.org/web/20190815232553/https://docs.microsoft.com/en-us/windows-hardware/customize/mobile/mcsf/enable-static-ip

**Comment by illfated** [comment] 2020-07-15 20:49
The entire section named "Customizations for mobile devices" has been removed from the Windows Hardware Development pages. I wonder if this has got anything to do with Windows 10 Phone not being developed any more, or if the pages simply have been moved to some other subsection of Internet of Things (IoT).

**Comment by illfated** [comment] 2020-07-15 20:56
Then again, there is the multitude of Microsoft Azure pages which also contains the topic "static IP address", but those are usually about more advanced services, like setting up Azure Kubernetes Service (AKS) or Azure Kubernetes Service (AKS) Load Balancer.

**Comment by exchange12rocks** [comment] 2020-12-07 16:14
In my opinion, the link hasn't made any sense from the beginning, because the article talks about a regular desktop PC, while that linked pointed to a content for OEM manufacturers of mobile devices. Techniques described there were never applicable to this article.

I think we should just remove the link - it has never been useful for this article.

**Comment by exchange12rocks** [comment] 2020-12-07 16:17
#5088

**Comment by illfated** [comment] 2020-12-09 17:14
Looks like this issue is resolved by PR #5088 and commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/7fafe54ce536b65ad5d0c210f22d64bb11e44d45. 

#please-close

**Closed by illfated** 2020-12-09 17:14 UTC
Labels: Pri2, remote-desktop-services/tech, windows-server/prod

**Comment by illfated** [comment] 2020-12-09 17:16
Likely relevant to https://github.com/MicrosoftDocs/windowsserverdocs.zh-cn/issues/21 as well, not sure how soon the change becomes visible in the /zh-cn/ translation.
