### ISSUE TITLE
Link to  Install or Uninstall Roles, Role Services, or Features is dead.

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windowsserverdocs#5368] opened 2021-03-15 14:19 UTC
The link to "Install or Uninstall Roles, Role Services, or Features" is dead. Please fix this.

Expected behavior:  Install or Uninstall Roles, Role Services, or Features link goes to a valid page.
Actual behavior:  Install or Uninstall Roles, Role Services, or Features link yields a 404.
Steps to reproduce: 
1. Go to page.
2. Click  Install or Uninstall Roles, Role Services, or Features .
3. Get a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6062bcb6-3aa2-b8b2-4a19-83581983dbe9
* Version Independent ID: 6e6854e3-bab7-fb4b-3a8f-9fff46e946ad
* Content: [servermanagercmd](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/servermanagercmd)
* Content Source: [WindowsServerDocs/administration/windows-commands/servermanagercmd.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/servermanagercmd.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment] 2021-03-15 22:32
Thank you for the report, confirmed to be correct. The 404 page even suggests the correct link:

Dead link: https://docs.microsoft.com/administration/server-manager/install-or-uninstall-roles-role-services-or-features
Good link: https://docs.microsoft.com/windows-server/administration/server-manager/install-or-uninstall-roles-role-services-or-features

Looks like the document page was moved to a different part of the directory hierarchy at some point.
I will make a PR to update the link to a working state.

**Comment by illfated** [comment] 2021-03-15 22:48
By the way, the last link at the bottom of the page (https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/servermanagercmd#additional-references), [Server Manager overview](https://docs.microsoft.com/en-us/administration/server-manager/server-manager) also produces a 404 page, for the exact same reason, the link assumes that /administration/ is a top-level directory and not a subdirectory beneath /windows-server/. I am adding the same solution for that link to my PR.

**Comment by illfated** [comment] 2021-03-15 23:08
There you go. PR #5370 is ready for review, comments and suggestions.

**Comment by Xelu86** [comment] 2023-03-09 20:09
#assign:xelu86

**Comment by Xelu86** [comment] 2023-03-09 20:10
Hey @rossmpersonal 

Thanks again for contacting Microsoft. We value your feedback. 

The issue raised with this documentation was corrected and this issue was not closed. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close

**Closed by Xelu86** 2023-03-09 20:10 UTC
Labels: Pri2, windows-server/prod, windows-commands/tech
