### ISSUE TITLE
Host VPs alloc

### ISSUE THREAD

**Issue by specator** [MicrosoftDocs/windowsserverdocs#2639] opened 2019-03-28 10:33 UTC
Hi there!

Assume we have 2 socket system with 22 physical core each with HT enabled (88 LP in Task Manager) and WS 2016 Datacenter installed.

Does this mean that if we use
`bcdedit /set hypervisorrootproc 4`

That 4LP from host system will be given exclusively to Root partition (to serve Network traffic, CSV workload, Driver interrupts, etc) and guests will not use this LP at all?

Or this setting just limits Root to use only 4 LP instead of 88 LP available on Host system?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24470750-984b-c639-9339-ec79c2cd3e2d
* Version Independent ID: 9fa54442-5c52-995c-046e-eb5bfcb95776
* Content: [Minroot](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-minroot-2016)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/manage-hyper-v-minroot-2016.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/manage-hyper-v-minroot-2016.md)
* Service: **windows-10-hyperv**
* Product: **windows-10-hyperv**
* GitHub Login: @allenma

**Comment by Bitterman88** [comment] 2019-09-26 05:44
hi Specator, were you able to find an answer ?
because I've set hypervisorrootproc 4 on Win10-based Hyper-V and true, processors visible to root partition were limited to 4. However all VM's were executed in context of these processors ONLY ! (ie. vmwp.exe and vmmem processes accounted CPU into these 4 cpu;s only). I dont understand what's the purpose of this setting then, if all VM's are no using remaining free CPUs but fight for those root CPU only ?

**Comment by specator** [comment] 2019-09-26 07:06
I didn’t find any answers and vendor keep silence too

> However all VM's were executed in context of these processors ONLY !
Here you can use performance counters to check that other cores working well

**Comment by Bitterman88** [comment] 2019-09-26 07:14
I found the reason for me (probably):

Since my Hyper-V is on Win10 1804, that client system is using so called “root scheduler” (https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types#the-classic-scheduler)

This scheduler means that you see utilization of VMs directly in root partition’s Task Manager (as VMMEM processes), but this is probably the cause why the bcdedit parameter doesn’t work as expected.

try to run :
Get-WinEvent -FilterHashTable @{ProviderName="Microsoft-Windows-Hyper-V-Hypervisor"; ID=2} | select -Last 1

if you have 0x4 (root scheduler), then you have same issue as me....

Im afraid to change scheduler type via bcdedit /set hypervisorschedulertype because its not recommended on Win10 :-(

**Comment by IngridAtMicrosoft** [comment] 2021-10-16 00:27
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Closed by IngridAtMicrosoft** 2021-10-16 00:27 UTC
Labels: Pri2, windows-10-hyperv/svc, windows-10-hyperv/prod
